### ISSUE TITLE
How do you get a higher upgrade max?

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#105]
@Ethismos mentioned that he had reached a maximum of 4 upgrades somehow. I have not yet gotten this.

How do you increase it? And the game should probably clue to towards this as well. E.g. when hovering the "X/3 Upgrades" text:

![image](https://cloud.githubusercontent.com/assets/4981659/15793450/54d29df4-29e4-11e6-8ed1-609e40cc1351.png)

**Comment by TravisGesslein** [comment]
You get +1 for first clears of all raids after Burning Cave (Chamber of the Seal is the first one to give +1). 

Btw regarding one of the suggestions you made in #53 [I will still answer that whole thing btw, as well as other issues here, just no time right now :hankey:], about giving players a better idea about what stuff is going to be unlocked and what they have to do for it, so there's always something in sight you're working towards etc:

The reworked questing system is supposed to be used for this (among other things). It will be called Book of Prophecies and contain prophecies which the player can find in the world in the form of scrolls, as well as prophecies that are just added at certain points (or are even just available from the very start of the game). Game mechanic wise they are just quests, but one special thing about them is that you can fulfill those prophecies without first acquiring the actual prophecy scroll and having it added to the book of prophecies. 

This is because initially we intended it to be used for all the secret stuff you can do in the game. I never liked the idea of being compelled to read a huge wiki for secret stuff that I'll never find out about and we wanted to give players a chance to find rare prophecy scrolls which basically tells you something like "get the burning seal, 10 essence of rage and use the burning seal in the chamber of the sealer". We didn't want players to require those scrolls first to do all that secret stuff though so they are basically optional. Anyways...

This would obviously be one of those things that could be formulated as a prophecy. One problem is that it wouldn't be visible to the player as a clear linear progression like "the next unlock step is xxx and you get yyy", instead they will have a list of several things that can be done at any one time. I think and hope that it's good enough for now, though. Our main problem here is implementation time. Implementing new UI always takes ages for some reason even though it's always the easiest to write in terms of code required.

**Comment by TravisGesslein** [comment]
I always end up with many more paragraphs than intended when I start writing :hankey:
