### ISSUE TITLE
Bulwark raider upgrade doesn't seem to work

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#114]
I've tried to test this a bunch and I can't get Bulwark to trigger anymore.

In this example, I had my raiders idle for several minutes in base (to clear the cooldown, if it was there).

I let rage generate above the 30 needed rage:

![image](https://cloud.githubusercontent.com/assets/4981659/15799581/ab3a0984-2a61-11e6-8112-f48b2645ab1e.png)

And I was below 20% hp several times. I was even at 68/3010 at one point - but in this screenshot I was at roughly 14% hp:

![image](https://cloud.githubusercontent.com/assets/4981659/15799588/ce96c0a2-2a61-11e6-85fc-46e312183559.png)

So either I misunderstood something, or it's not working as intended.

**Comment by askebv** [comment]
When I don't have this upgrade enabled, Bulwark triggers just fine (when I have 30+ rage and an enemy is attacking).

**Comment by TravisGesslein** [comment]
Yeah looked like a small bug. Also we changed the skill so Warriors now dynamically detect when they are about to die and trigger bulwark using that, using their damage taken per second. This is better than a flat check for "less than 20% hp" or whatever because it will work regardless of how much damage the enemy does. if the boss is able to two shot your warrior, the warrior can now detect it and trigger bulwark accordingly.
