### ISSUE TITLE
Health and Mana bars aren't readable, for me

### ISSUE THREAD

**Issue by thorbrian** [Heishe/idleraiders-second-run#125]
The resolution of the text on health and mana is pretty terrible - seems like there is a lot of dead space under the raider lists, so would be nice to make the text bigger

![image](https://cloud.githubusercontent.com/assets/11687574/15802004/34fd9534-2a5b-11e6-88fe-fc12c2cd8c52.png)

**Comment by TravisGesslein** [comment]
Could you tell me what kind of display resolution you play with?

**Comment by TravisGesslein** [comment]
I think what's rather the problem is the text rendering technology itself (I don't think we use the pixels you have efficiently). We just use the default that is provided by the engine we use which isn't that good, but I've been wanting to experiment with some other approaches for a while, like signed distance field text, especially some recent research has improved the technique a lot. But no time for it at all :hankey: 

Can you tell me if you have similar problems for other text or numbers in the game? Item counters, item description text, buff stack counters, buff timer text, etc?

**Comment by thorbrian** [comment]
1366 x 768
I don't remember caring about other text being unreadable, but they are a bit of a mixed bad.
 I've been reading description text no problem. 
Item counters I do often misread - like 3's for 9's, that kind of thing. I never even noticed any text related to buffs, actually.

**Comment by TravisGesslein** [comment]
Whew, this is complicated problem. The reason they are unreadable is that with a 1366 x 768 display, given that the game window itself doesn't even use up all of the page size, the render resolution of the game is something like 640 x ....   or something similar. In other words: Very small. This makes it extremely hard to render small text sharply as well as fast enough to not slow down the game significantly. 

We're mitigating this by making the character views on the left a bit bigger (this is what this issue is for), as well as adding a fullscreen mode for browsers that support it. Not sure if this will make it into Beta Patch 7 (which will go live sometime later today). Either way the character views will be a bit larger. The text won't look super crisp (like the text here, because browsers have some mad text-tech which we can't implement right now) but it should be a bit better. When the fullscreen mode is added, everything should be perfectly readable even on small resolution devices.
