### ISSUE TITLE
Reflecting item set bonus in statistics

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#129]
The full Might of the Sealer set gives 100% to rage regeneration for all warriors - but it doesn't show in statistics. Is this intended? I know not all set bonuses can be shown in the stats, but some can. And I think they probably should be.

And also - what does the Mage set bonus do?

> Mages receive one ability from Skillbook: Inner Combustion (does not use ability slot)

The only thing I can think of is that it pretends I have an extra ability slot, and that it put the _Skillbook: Inner Combustion_ there - effectively granting one equipped fireball skillbook a free cast every time it crits. And thus making it possible to have one mage with 2 fireball skillbooks affected by inner combustion, while also having ignite. Is that right?

**Comment by TravisGesslein** [comment]
Oh, energy generation is different from regeneration and degeneration :hankey:. When your warrior attacks something or is attacked, they generate a fixed amount of base rage (currently 3 when attacking, 2 extra when critting, and 4 when being attacked). This base amount is scaled by the energy generation modifier, which is 100% by default (and 200% if you have the set bonus, but there are also other items which increase this value). 

Energy regeneration meanwhile is the thing that regenerates energy every second, and energy degeneration removes energy every second. Mages and Priests have a base energy regeneration of 1, Archers have 10, and Warriors have 1 but also energy degeneration of 2 which results in the loss of rage every second.

So the set bonus makes it so that all hits of your Warriors generate 6 rage (or 10 if they crit), and they receive 8 rage for being hit. The effect of this is probably easily underestimated. A basic warrior without attack speed bonuses and no bonus rage generation has extremely barely enough rage generation to use Mighty Blow once every... [very long amount of second] seconds or so, because the Warrior degenerates almost all of the rage gained from one attack in the cooldown period between one attack and the next. With 100% increased rage generation, your effective rage gained per second goes from like 0.5 to 4.5 or something.

A more easily distinguishable term for rage/energy generation would probably be better, any ideas?

**Comment by askebv** [comment]
Thanks for the explanation. That's actually already how I understood it, but I somehow thought that the rage regen stat in the statistic would reflect the energy generation for warriors. But I suppose that's because it's a generic concept? Is/will it be possible to change the generation/degeneration rate - and if not, wouldn't it be better to replace it with a generation stat for warriors?

**Comment by TravisGesslein** [comment]
Oh I forgot to mention that. I will add the rage generation stat to the stat screen (it's just missing in Patch 3) just in time for Patch 4. And to the second part of that question as to whether we will be able to change regeneration and degeneration of warriors: Yes, some buffs already do it, and I'm sure we will introduce items for it as well (e.g. some unique item that removes or reduces the rage degeneration of warriors)

**Comment by askebv** [comment]
Ah right, the well already does it.
