### ISSUE TITLE
Does the "Protective Shield" skill exist yet?

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#144]
There's a raider upgrade that references the "Protective Shield" skill:

![image](https://cloud.githubusercontent.com/assets/4981659/15807572/0ea0bbca-2b62-11e6-9fbd-c26dda9c9a7e.png)

It sounds like a priest skill (like the [Power Word: Shield from WoW](http://www.wowhead.com/spell=17/power-word-shield)) but I've never gotten it. I've cleared all raids many times now, including the Dawn Fortress.

Have I just gotten unlucky, or is it not in the game yet?

**Comment by TravisGesslein** [comment]
Oh, it was in the game in the alpha, but we haven't re-introduced it yet (No particular reason, there are plenty of skills not yet dropped in the beta because they will drop in boss encounters later in the game). It's not exactly like the WoW shield, instead it gives the targeted raider a damage reduction against all damage types buff. Basically a "Shield Block" for priests which they can give to all other raiders.
