### ISSUE TITLE
Can't equip archer hat

### ISSUE THREAD

**Issue by Noxos** [Heishe/idleraiders-second-run#15]
![idleraiders](https://cloud.githubusercontent.com/assets/19698037/15728528/8956779e-2822-11e6-9557-e13ff61f8d79.png)

**Comment by TravisGesslein** [comment]
Looks like there may be some transmog bugs left. Keep in mind though that you'll probably want to equip the hat using the equipment slots on the left. The slots on the right are just for cosmetic purposes: Any items equipped here just override the look of whatever body parts your raider has already equipped in the slots in the left window.

**Comment by Noxos** [comment]
I see.  I didn't even realize there was another spot to equip items until you mentioned that.  It was able to be equipped and it's appearance showed up when using the correct equipment slot on the left.

**Comment by Noxos** [comment]
On the subject of transmog, I should probably mention that I equipped a sword into the transmog slot incorrectly, and when I reloaded the game it had vanished.

**Comment by TravisGesslein** [comment]
Weird, should have been fixed in a patch that we uploaded yesterday. It's possible you received a cached version of the game (i.e.  your browser used a local copy instead of downloading the latest version). We'll add some browser magic in the future to force browsers to update to the newest available version instead of using a cached copy.
