### ISSUE TITLE
I can't figure out how to use an "Enchantment"

### ISSUE THREAD

**Issue by thorbrian** [Heishe/idleraiders-second-run#174]
I may be dense, but I've got enchantments "blessing" and "greater healing" but I'm totally stumped as to how to make use of them.

I've beaten every raid, gained wisdom a few times, got burnt out seal, built every building that is offered to me

I've tried right clicking, double-clicking, dragging, right dragging the enchantments everywhere I can think of (on top of items, on equipped items and abilities, on raider portaits, on icons)

Am I supposed to be able to use them?

**Comment by askebv** [comment]
I swear I had a topic on this before, but I can't find it.

I haven't played the alpha for a long time, but I did the other day, and it turns out they have enchanting in that. So it's probably just something that they'll implement here too. I neither see it here yet though.

**Comment by TravisGesslein** [comment]
Yeah, we removed it from the Beta for now since it's too bare-bones (it's actually fully functional for Enchantments already, Enchantments basically enhance or change skillbooks) and will be reintroduced once we get around to creating more items for the crafting system. That and the reintroduction of the modified skill system (Book of Prophecies) will be the first thing we start working on once we close down remaining bugs here, btw. I know there are many issues left but many of them are suggestions or questions, I think we will have most important bugs squashed by Beta Patch 5.
