### ISSUE TITLE
What I love about this game

### ISSUE THREAD

**Issue by thorbrian** [Heishe/idleraiders-second-run#177]
I just wanted to provide some feedback on what I love about this game - not just what's done well that other games may do well too, but what for me it does better than any other game I can think of

What I love is the cycle of collecting new gear and building a new combination that gets a better result in a specific way. Not just making it better, but trying out different options that are all viable but better based on circumstance or combination.

The burned out seal is a great item in this respect - it's unique so I can only use it on one raider, it's got a distinct power that's special and unlike any other equipment, and it's a dramatic enough effect that for the one raider you use it on, it's a game changer for how to build him. It's great.

One thing that could enhance the fun of this is more situations where a certain combo has a strong advantage over another combo, where normally the relationship is reversed. There are some more obvious examples of this one could capitalize - like calming shot - a situational skill that's basically useless most of the time, where if the boss had some major buff, it would be beneficial to notice it, and start using that skill. I didn't find any such case, FWIW (didn't affect the lava dog growing for instance), but it would have been fun to notice such a case. But the most interesting ones for me are ones where i's much more subtle. Like I had cases where I discovered my priests were mana starved in a long fight, so I built for priest mana regen. But it would also be fun to have a match where I needed to build for burst instead. Like maybe if there was a mana depleting high attack speed priest item, against a boss that had a period of fast damage.

Anyways, keep up the good work :) I find that idle raiders is a more fun and more pure expression of tweaking gear to try and find new combos than I get anywhere else, which is awesome. Thanks for what you've built so far!

**Comment by TravisGesslein** [comment]
Glad you like it :D Bad news though: Burned Out Seal (and another related item) are supposed to be Warrior weapons, will be changed in Patch 4. Don't worry, other classes will receive unique items like this as well. 

Also keeping this open for the glitch you mentioned where Calming Shot didn't affect the enrage of our lava dog.

**Comment by TravisGesslein** [comment]
While investigating it seems like Calming Shot is working as intended: It should remove the enrage effect from Lavrador once it starts. In case you have many other different active skills equipped, make sure to buy the Town Hall and put Calming Shot in the front of the skill priority list. 

Also, there's a Raider Upgrade for it which changes the ability to make sure it's only used if the enemy has at least one running buff (we kept it separated out as an upgrade instead of forcing this behavior all the time in case players want to maximize DPS while still having this skill equipped - it does a little bit of damage after all and not using it until the enemy has a buff reduces your damage output a little bit). 

If the Raider Upgrade isn't active it can often come to situations where your archers use the ability and then it will be on cooldown for most or all of the uptime of the enemy's buff. Otherwise it definitely works with all kinds of buffs on enemies... Lavrador's enrage is the first example, but a few select bosses of later raids have buffs like this as well. There are also certain (secret!) situations where it can be useful on farm maps.

**Comment by thorbrian** [comment]
Well... burned out seal and arctic honor are a lot less... interesting, now. Even without the sword nerfs, warriors are the one class I never used those two items on.

FWIW, I tried them both out on my non-tank warrior, and arctic honor seems like a worthless item, IMHO. Even with the big nerfs to rage gen boosting items, I just always have enough rage for skills all the time, as the warrior skill cooldowns relative to the costs are so big I frequently have full rage bars.

I'm tempted to keep arctic honor equipped, just because I'm hoping it's part of some kind of secret as a unique item (I've been keeping an essence of rage equipped hoping it has some purpose), but I don't know how I'd even know if that were the case
