### ISSUE TITLE
Priest doesn't heal when he should with Overheal upgrade on

### ISSUE THREAD

**Issue by thorbrian** [Heishe/idleraiders-second-run#180]
When I turn on the Overheal raider upgrade, a priest with 128 healing power (from burned out seal) isn't healing raiders that need it. See image, where raiders are damaged, overheal is on, but priest isn't healing.

![image](https://cloud.githubusercontent.com/assets/11687574/15848254/bac8c18e-2c40-11e6-8fcc-9bcc7ed54ddf.png)

note that since priest has arctic honor as well, when overheal is off, he's healing every couple of seconds, while I've seen him not heal while archers die with overheal on.

**Comment by Talisca** [comment]
The actual healing amount is affected by the received healing modifier of the raiders and the healing output of the healer as well as the formula: healing_amount = 50 + healing_power \* 5

So you've got a healing_amount of about 690. In this case the priest would never heal your archers because of low max hp.
