### ISSUE TITLE
Suggestion: Let monsters do not pursue when You press Rest button.

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#184]
When I feel that My team begin wiped by monsters press Resting button. Remains of My team try to escape from map. They move to the entrance and monsters still pursue them. So it is huge amount of monsters stays at entrance and when I try second run My raiders die in several second cause they do not appear at one time.

**Comment by TravisGesslein** [comment]
Mhm.. how about this: Monsters go back to their spawn locations when they don't have targets in sight anymore?

**Comment by askebv** [comment]
Actually, I like Heishe's suggestion for the opposite reason. Right now, you can abuse it due to them pushing each other out of the map over time. In the end you'll have only one enemy left, and constantly having your raiders come in and out will eventually get the enemy down, without any user interaction. So over time, you'll eventually get them down, as long as you can kill enemies with a full team of low mp raiders, in the 10 seconds that Bulwark lasts. Of course you can't be one-shot by the monsters, because then he'll never trigger Bulwark.

When I want to actively push my farm level, I usually let my raiders rest, then go into single target practice mode, and then when it starts, I launch auto-increase mode, instantly putting all my raiders into the farm map with full mana and cooldowns for a burst damage effect. I always get at least one monster kill out of this strategy.

**Comment by DaemoniaV** [comment]
Heishe suggestion is like to me.
