### ISSUE TITLE
Suggestion "More" button for - Scholar Tower

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#188]
I have 8 books of skills improving Frost Shard and 10 book for Magic Missle but have only one Magic Missle. Let it be option to add random book in tower for reasonable price)))

**Comment by askebv** [comment]
That is how it was in the alpha - but I think I would prefer if it worked differently. After all, the scholar's tower is mostly meant for beginner skills.

Instead I think it should offer something like tiers of books, divided by classes, and provide an unlimited amount of the ones available. Over time, with progress or given specific quests were completed, you could unlock new skills.

Because as it is now, it's very random which skills you get starting out. You could get a super OP starting build, or a pretty sloppy one for a long time. And gold is pretty hard to come by at first, and then later you'll get more than you'll know what to do with, and less things to buy. So making a "more" button is only going to fix the lack of luck near the end game.

My 2 cents anyway.

**Comment by TravisGesslein** [comment]
The reason it's random is that it kind of forces people to play with what they have in the beginning, and try out things they wouldn't have otherwise, while still allowing them to eventually do whatever they want to do, because after a couple of days playing (which is not that long for how much time I hope people will spend with this game) you will have most/all skillbooks which there are available anyways.

Some of them are going to be very situational (something like Charming Shot) and as such most players would probably prefer consistently seeing skills which always have some application (like Healstreak, or the various mage skills). As it stands I don't think that is much of an issue because of what I mentioned above. However, if players really find this bad for the game I could work around it in various ways, for example I could give a higher spawn chance to skillbooks that have not yet been sold by the Scholars Tower, or which at least are not currently sold by the Scholars Tower.

**Comment by askebv** [comment]
I understand what you mean, and in principle I agree. But at the time, early game is not full of many things to do, if I remember right. After you have all your raiders, and have most of the tents, there's a steep grinding curve where progress is severely dictated by your luck in scholar's tower (and time). If you add other features that rewards active gameplay at that point, then that's a fine alternative in my opinion.

In other words, the core of my criticism isn't that much about the randomness - because as you say, the vast majority of people are statistically likely to get whatever they want eventually. But there needs to be something else to do at that point.

At first I was interested in obtaining the raiders, and since it was fairly quick, it was interesting to observe how my team got stronger fast, as every new raider arrived.

Then I had the tents, which seemed pretty expensive, but at least made some progress. After that, comes the skillbooks and the levels. Skillbooks seemed awfully expensive and I remember that I suddenly were forced to leave the game running for hours, just to get one skillbook. And often, it wasn't even a skillbook that would help much. For me, it felt like most of my progress happened through waiting. Waiting for gold and exp. And the primary reason that kept me going (apart from knowing the game already, and being enthusiastic about beta-testing) was seeing future raids, and the mechanics of future skills and future equipment.

After what felt like a lot of waiting, I got to level 50, with a decent set of skillbooks on hand, and then it felt like I was getting back in control. Now I suddenly had the option of gaining wisdom, and was getting more and more skills and equipment at my disposal.

Anyway, I'll end this here - you probably get the point. I think your future plans of questing and such might bring back some of the possibilities of active gameplay as well, so I'm sure it'll change eventually.

My 2000 cents. (I know how to write very long paragraphs too :hankey: )

**Comment by TravisGesslein** [comment]
Thank you for the thoughts. I think this is very much related to the other issues where this was mentioned. We will put in a lot of early game stuff via book of prophecies (and also, for completely new players, some tutorial stuff) so I think that should fix this issue handily.

But it's good to keep in mind that we have to take care not to make the progression to much "wait to get lucky"-based, and a bit more consistent, so I will keep this issue open until then.

**Comment by TravisGesslein** [comment]
Plan for patch on monday: 
- The skillbooks are (internally, not visible to the player) split up into 'core' skillbooks and 'extra' skill books. The extra ones are stuff like Charming Shot, while core ones are stuff like Magic Missiles. The both are separate, but the extra ones will only show up with a relatively low chance in addition the the core ones (so when they drop, you get two skillbook drops in the scholar's tower).
- Skillbook chances for showing up are biased such that skillbooks that have the lowest occurence count in scholars tower inventory + main game inventory + equipments of raiders have a higher chance of spawning.
- There are now various higher level skillbooks (e.g. Skillbook: Shield Block Level 2) in the game, and they will start showing up in scholar's tower at certain points in the game (at some point the level 1 versions will just stop showing up). I should note though that this starts pretty late in the game. The earliest you will see level 2 skillbooks show up is Frozen Coast, but then only if you get lucky (the chance for higher level skillbooks to show up increases the higher  you get in raid tiers).
- In addition, there are various global skillbook random drops and also skillbooks that can be crafted by the dwarven runesmith.
- Of course, some bosses will also drop skillbooks sometimes.

**Comment by TravisGesslein** [comment]
I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
