### ISSUE TITLE
Hail of Arrow cooldowns aren't identical

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#196]
As you can see, one finishes several seconds before the others. But they start out at the same time:

![image](https://i.gyazo.com/9a7f20cc6446a75ab02101801c5a673f.gif)

I'm not sure what the purpose of this is, if it's intentional. To tell who used it? It always seems to be the same who gets it done faster though, so I'm not sure if it really works that way.

**Comment by TravisGesslein** [comment]
More or less intentional. The reason is most likely that one of your archers has a higher attack speed, which reduces the cooldown of all skills, which is what you can see here. The archer who finishes first will be able to trigger the cast for both of them - this also is intentional. 

What's not intentional is the out of sync cooldown. Unfortunately I don't think I will fix it, lots of code for very minor fix.

**Comment by askebv** [comment]
Fair enough. And you were right, 121% vs 107% ats.
