### ISSUE TITLE
Improvement - Auto-Raiding on first unfinished raid.

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#198]
Let the Raiders do one try on first unfinished raid.
I can easy finish R3 but last Boss of R4 wiped My party easy. Items from R1-R3 do not help anymore. I need drop from first, second and third Boss of R4 but can gain it only in manual raiding(

**Comment by TravisGesslein** [comment]
The reason the latest raid is disallowed in the auto raid mode is not because your raiders most likely won't manage it, rather it is because I wanted to encourage players to experience the newest raid for themselves instead of letting raiders auto idle over it. 

What does everyone else think? I'm not opposed to relaxing the restriction such that you can auto-raid the current raid as long as you have killed at least one boss on it once.

**Comment by askebv** [comment]
I think it's too much if you can just leave it on auto-raid and eventually go through new raids you've never manually beaten.

Preferably, I'd like the raids to require more strategy, experimentation and planning - and thus also have mechanics to them that _required_ new setups as you advanced.

Either way, I wouldn't personally find it enjoyable for it to auto-brute-force its way to victory. That makes advancing just too easy, leaving time as the primary constraint/challenge. But if others disagree, then I wouldn't mind Heishe's suggestion where you can auto-raid if you already beat one boss.

**Comment by DaemoniaV** [comment]
May be let raiders try to beat only previous killed monsters. When last previously killed boss done they do not advance but auto retreat and begin usual map farming.

**Comment by TravisGesslein** [comment]
Well, in practice I think this actually wouldn't that big of a problem. I think the way active as well as mostly idling players play wont change because of it. When you auto-raid but are mostly an active player, what happens is that  you return after a couple of hours, check the new stuff you idle farmed, maybe make some build adjustments and then make an attempt at the new raid. I think this is the same for mostly idling players with and without the above restriction lifted, because raiders won't beat a new boss until you equip newly farmed items. Or maybe I'm missing something. 

Some further thought:

First of all we want to accommodate both players that primarily want to idle and check in once in a while, as well as the players who actively try to advance as quickly as possible. Accomodate meaning that we don't want players who primarily idle to ever hit a wall where they won't advance (this is one of the reasons why we left raider leveling in after level 50 instead of just capping it off there). That is only for the main raid progression by the way, it doesn't concern optional content like optional raids or other stuff we may or may not introduce that may or may not give especially awesome rewards :hankey: Also don't misunderstand, this also doesn't mean we want players to be able to idle to win. It just means that, for example, the equipment drops from the primary raid bosses should be enough to beat bosses after that. It's just going to take a lot longer than for someone who is more active in playing the game.

Your raiders won't beat a new raid without player participation, because at the very least you have to equip newly acquired items. If you stick to that, you will advance very slowly, because experimenting with builds and upgrades as well as actively using stuff like scrolls and potions in raids is a major boost to how early you can beat new bosses. But it means you CAN do it, if you really just prefer idling most of the time and checking in on your raider's progress so to speak.

At the same time there are already major benefits to playing the game a bit more actively - besides the stuff mentioned above there are also things like events (more to come than are already in the game) like the Efreet event which enables you to charm the Efreet and use it to buff your raiders in preparation for a tough raid, or the Time Warped Cave (/arena) which gets you loot faster if you regularly visit it instead of being AFK most of the time.

Also, we can adjust the balancing of future raids such that active playing and strategizing is also encouraged more.

**Comment by TravisGesslein** [comment]
I think I'll try it out, if active players find it's disruptive to the feel of the game we can remove it again.
