### ISSUE TITLE
Not getting the patch notification anymore

### ISSUE THREAD

**Issue by thorbrian** [Heishe/idleraiders-second-run#200]
I leave the game open in a tab in the browser (like when I go to work, go to sleep...), and since patch 4 came out, I've not seen any notifcations about it. options clearly shows patch 3.

When exactly are notifications supposed to show up?

**Comment by TravisGesslein** [comment]
They are supposed to show up within 30 minutes of us uploading the patch. We'll look into it

**Comment by TravisGesslein** [comment]
Actually, this is a bug that was fixed with Beta Patch 4 :hankey: You likely received the notification but missed it because it disappeared. With Patch 4 we removed the time restriction of those kinds of notifications, they will now stay until you click on them instead of disappearing automatically after 30 minutes.
