### ISSUE TITLE
Frozen Shield tooltip overstates damage reduction effect (says 6% does 5%)

### ISSUE THREAD

**Issue by thorbrian** [Heishe/idleraiders-second-run#202]
Frozen shield tooltip says it does -6% damage reduction

but when I equip and unequip one, my damage reduction stat only changes by 5%

**Comment by askebv** [comment]
I think this might be related to the fix of #179

Mine says 4% when I try to unequip.

**Comment by TravisGesslein** [comment]
This is intentional, the damage reduction of that particular stat becomes less effective the more you already have of it. Unfortunately we can't show the actual value it would take in the generic item description because the result depends on the raider itself. 

But you can see the actual change using the comparison stats in the stat screen, for example when you click the item in the inventory and then hover over an equipment slot of one of the raiders it will show the change in a red/green or gray number next to the 'damage taken by all ...' stat.

**Comment by TravisGesslein** [comment]
With that stat in particular we made the trade off between showing the user an actual percentage of damage reduction vs instead using something like an abstract armor value (like in many RPGs) that maps to some curve underneath. We figured the first is much more intuitive even if it doesn't completely match up with the actual values a raider with multiple items with those stats will receive.

**Comment by askebv** [comment]
Yeah I think it's nice. When are grey numbers shown btw? And could you add a decimal to the damage reduction so it's easier to see the effect? After all, there's a big difference between 3, 4 and 5% when you get down in low numbers.

**Comment by TravisGesslein** [comment]
They should be shown when there's no change at all, or maybe we don't actually show anything in that case? :hankey: And sure! We can add decimal digits.

**Comment by askebv** [comment]
Thanks! For now, it's not necessary to add digits to all the other pecentages - because they're all flat increases, so it'll just always say ".0".
