### ISSUE TITLE
Suggestion: Easy class-filtering toggle

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#220]
The two most common scenarios you'll need when filtering which items are shown are
1. All items
2. Items suitable for a single class

But I guess it's also nice to be able to do more custom sorting like it is now too.

So perhaps you could make right click do it differently. E.g. when right clicking a class-head, it always filters out all other classes. But if the right clicked class is already the only one shown, then it shows all classes.

**Comment by Talisca** [comment]
I like the idea of deactivating all other classes with one click.

The current filtering works like a or-conjunction, so all items for the activated classes are highlighted. 

I also thought about an and-conjunction so that you could filter for all items, which are equippable for each highlighted class (like the Hitstreak Skillbook - it's applicable to both Warriors and Archers).
