### ISSUE TITLE
Question: Does Resting between Raids has any timer?

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#228]
Have noticed that My raiders go to the next Raid only with 2/3 of mana.

**Comment by askebv** [comment]
Yeah I think it's timed. My mages never went with full mana before the red priestess upgrade.

**Comment by DaemoniaV** [comment]
How many Churches You have?

**Comment by TravisGesslein** [comment]
Yeah it's on a hardcoded 30 second timer. I'm not sure if it's necessary anymore, initially I added it so you don't get into situations like mages with 1k mana literally standing in the base for 1000 seconds because the player for some reason hasn't built any churches, but I suppose that's kind of a corner case that is very unlikely and I don't know if we even need to handle it. What do you think about it?

**Comment by DaemoniaV** [comment]
First need to build a cap of church and look into restored amount of mana)

**Comment by askebv** [comment]
In my experience, 30 seconds is good. It also encourages people to buy churches. And even without full mana, we should be able to easily destroy all raids except the newest one we downed. Especially if we barely made it on manual mode. So it's only a fair disadvantage, in my opinion.

But I think it'd be nice if you made an extra check, where if all raiders have full mana, and nothing on cooldown, then you just start. This will especially be relevant later on, I think, since auto-clearing that many raids, takes such a long time. And in the end, we might only have a few minutes of farming, and then the rest is raids.

**Comment by TravisGesslein** [comment]
You mean full energy only, disregarding HP etc? Currently it already checks if raiders have (near) full HP and energy and sends them away.

**Comment by askebv** [comment]
@Heishe Yeah I noticed after testing it some more. I don't mean a disregard of HP - but I thought it should wait for cooldowns on skillbooks as well.

But I'm not sure. It's hard to tell because I'm already at the state of being overpowered, and thus it works fine as it is now.
