### ISSUE TITLE
Bug the Raid that will be open by Map again dissapeared.

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#229]
Suppose it happened when I load cloud save.

**Comment by TravisGesslein** [comment]
You mean like #110?

**Comment by Heishe** [comment]
I think what's rather the problem is the text rendering technology itself. We just use the default that is provided by the engine we use, but I've been wanting to experiment with some other approaches for a while, like signed distance field text, especially some recent research has improved the technique a lot. But no time for it at all :hankey: 

Can you tell me if you have similar problems for other text or numbers in the game? Item counters, item description text, buff stack counters, buff timer text, etc?

**Comment by DaemoniaV** [comment]
Yes. When I sofе reset this Raid move to the first place before Crypt. I leave game idle on Auto-Raiding on CPU at work and go home. When I home I use Team Viewer to close game on my work CPU and start game on my home CPU. Load from cloud and it dissapeared.

**Comment by TravisGesslein** [comment]
Mhm... okay thank you we will fix it asap

**Comment by TravisGesslein** [comment]
Oh, was that a savegame you just played, or an older one from Patch 4 or whatever where Dawn Fortress was missing? I think savegames from when the bug was still in the game need to unlock the raid again using the map before it works again...

**Comment by TravisGesslein** [comment]
@DaemoniaV pls help

**Comment by TravisGesslein** [comment]
After some testing we are relatively sure this is because of old savegames. If you get the map again you should be able to unlock it and get the map back into the raid 'inventory'.

**Comment by DaemoniaV** [comment]
Sorry do not vieq You comment earlier. Today again cath this. There is no save 100%. I load game and check the raid it was there. Then soft reset and it dissapear. Did it normal?
