### ISSUE TITLE
Spiked slime event

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#243]
What this event do (beside visually changing the slimes)? The only advantage I see is that there's more spawns of low hp monsters, than you'd otherwise be able to get - so potentially a minor gold advantage.

Do they drop something special or anything else?

And if not, do they still appear later on? I don't see any advantage from them when you're able to one-shot later farm maps.

Either way, I think this event should have more use in the future or at least be changed.

**Comment by TravisGesslein** [comment]
Somehow never answered this one. In case anyone reads this after it's closed: The intention with that event was indeed just to have a large amount of low HP monsters that grant easy access to a short burst of gold. Events were never supposed to be major things to look forward to, but more along the lines of something neat in case you are coincidentally watching the game while they happen (instead of idling), or indeed something to min-max progress in case players feel like 'speedrunning' through the game. Though admittedly the entire event system a bit orphaned in a way, there are not enough (different ones) of them so when one of them happens it can feel weird when nothing major comes out of it.
