### ISSUE TITLE
Show 'new item' label on inventory button when new (unviewed) items have been looted

### ISSUE THREAD

**Issue by TravisGesslein** [Heishe/idleraiders-second-run#247]

**Comment by askebv** [comment]
Hmm I'm not sure it's good this way. Because often I've looted so much that it's kinda tedious to mouseover all "new items". I think it should just show the 'new item' label on the inventory button when new items have been looted since last you looked at your inventory.

And maybe I'd actually also prefer if there was an option to remove the "new item" label from all items, when I close the inventory.

**Comment by TravisGesslein** [comment]
I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
