### ISSUE TITLE
Cost of Soft Reset..

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#282]
Does it direct formula Artifacts*10?
It seems Me very high price. I reach 4000 artifacts in several hours. But 40000 of gold it is several days!

**Comment by askebv** [comment]
#270 Yeah it's a high price. I think it might need tweaking but we'll see. It'll definitely mean that you'll need to upgrade "more gold" a lot if you want to do quick soft resets over and over.

**Comment by DaemoniaV** [comment]
It very weak bonus. Fro example +10% gold from 30% to 40%. Cost 2000 AA = 20 000 G. My day income about 20 000 (but may be less). So it give me 2000 G in one day. So it need 10 days just for return spended money.

**Comment by askebv** [comment]
Offline gains will probably remedy a big aspect of this. But if you're running the game 24 hours straight, then you should get more than 20k gold. Otherwise you're not farming the best place for gold. With Hail of Arrows, Cleave, 5/5 Increased Monster Count and 5 More Gold, I'm getting around 7k-8k per hour in farm level 10. Probably only 5k if auto-raid mode is on.
That means it would take 3-4 hours to get back the 20k invested in the 30%->40% upgrade. Granted, this is with the best equipment currently available in the game.
It probably still is a bit too expensive - we'll see though. Currently, I think it's probably good for pacing that it's possible to spend idle gold to speed up progress.

**Comment by TravisGesslein** [comment]
Closing this as there are newer issues like #438 are about the same problem.
