### ISSUE TITLE
Visibility of health numbers

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#284]
It's not as bad as it appears to have been on a small screen (#125), but this new fix makes the text a lot harder for me to read:

![image](https://cloud.githubusercontent.com/assets/4981659/16097346/a247e9dc-334d-11e6-9656-13dd7136132b.png)

It's probably a pretty difficult thing to tackle. But my best suggestion is to look at color management, resolution detection and/or fonts.
For color management, you could make an option to show individual symbols/numbers as black, if they were on a light color background. I think the green, yellow and orange colors would be better off with a black font. The blue, red and empty space is good with the white.
Resolution detection is basically about handling the rendering differently above or below different hardcoded thresholds - or giving players an option to manually toggle between text render modes. This could for example to disallow anti-aliasing, and thus have sharply contrasted symbols.
And my point about fonts is just about finding a font that clearly distinguishes similar looking numbers like 3, 6 and 8 - and sometimes even 0, if it has a dot in it. Sometimes also 5 and 6, but your current font seems to handle that well.

Here's a quick mspaint example of how the black color thing could work:

![image](https://cloud.githubusercontent.com/assets/4981659/16098075/a1063610-3351-11e6-9a7f-53b20c7b022e.png)

**Comment by askebv** [comment]
As a sidenote, buff text is also pretty hard to read for me on certain backgrounds now:

![image](https://cloud.githubusercontent.com/assets/4981659/16108448/766fb8b6-33a3-11e6-9ed4-743416e6f7e4.png)

**Comment by TravisGesslein** [comment]
The problem here is mostly combination of a :hankey: font for low font sizes (lots of thin lines, lots of space between characters and their curves, adding outlines makes it even harder since they are usually very thin features, etc.) and bad rendering. I will continuously improve this over time as I get around to it. Next patch should already have quite some improvements. 

Current patch text left, patch 8 text right. Still the same font, but much better looking imo.
![textold](https://cloud.githubusercontent.com/assets/2046189/16114458/a469be1a-33c1-11e6-8f9d-6f15af3eff89.png)

**Comment by TravisGesslein** [comment]
Actually, the one on the left is already a slightly improved version from the one that is currently live :hankey:

**Comment by askebv** [comment]
@Heishe Looks great to me, in high resolution. I also tried more Kongregate-friendly sizes and several of them looked good as well:

![image](https://cloud.githubusercontent.com/assets/4981659/16169584/64fcc654-3534-11e6-975b-21f2319dab37.png)
