### ISSUE TITLE
About drop again...

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#288]
Sorry for my annoying. I am again rebuild My team and they now 50% kill Yeti on last raid. But we do not take it into account. Count another...
I kill Yeti and Centaur 16 times (for 2 days) manually. My drop chance 500% and 4 times it was first clear after soft reset. Thorbrian  mentioned 10% drop. How did it work? I have 500% drop - mean this is 10%*500%=50%?? If it so... Do You believe that You can drop coin one side 16 times in a row?
p.s. I will NEVER see some drop from Ravaged Adobe. Zero items!

**Comment by askebv** [comment]
Unless they have a failsafe, it's always possible to be unlucky with probabilities. Even with 99% chance to drop something, it's _possible_ to do it thousands of times, and still not get it. It's very _unlikely_ but it can happen. And we always seem to believe that the rare cases will never be ourselves.

Probabilities aside, it could be a bug - but I haven't personally had any issues with it. Perhaps you should send your save file to social at pitforest dot de and have them investigate, if you really think it might be a bug.

**Comment by DaemoniaV** [comment]
Did You notice some drop form Adobe? Besides that set items.

**Comment by TravisGesslein** [comment]
Oh, the drop rate upgrade only affects 'global drops' that can drop everywhere, like random healing scroll drops, or the global item drops you can get. We can't really modify boss drops like that, unless we add lots of special handling depending on item rarity and making sure that the probabilities still make sense, etc. (if we just increase the drop % of items weird stuff will happen, like items never dropping because something before it in the accumulated probability loot table has 100% drop chance which shouldn't be possible).

Also I don't want to mess with boss drop rates in general. The rarity of those items are specifically designed with a special feeling of chasing after certain items in mind, changing that via upgrades will only mess with it. 

We should probably clarify how it works in the loot chance upgrade description.

**Comment by TravisGesslein** [comment]
Regarding the other stuff though: Are you saying you aren't getting ANY items from Ravaged Abode?

**Comment by TravisGesslein** [comment]
Oh just looking at the monster definitions, somehow their loot tables were removed... sorry about that

**Comment by DaemoniaV** [comment]
16 times in a row I do not get ANY drop from Ravager Adobe.
It is still very small chance that I miss animation of getting item and looted items was already looting pevious raids. May be You share name of drop able items from Adobe?

**Comment by DaemoniaV** [comment]
Sad stuff(((

**Comment by TravisGesslein** [comment]
Lol I'm very sorry, that would explain why you are so "unlucky" with the drops, they don't have any :hankey: . Will be added in Patch 8.

**Comment by TravisGesslein** [comment]
On a side note I know some of you already had the set completed, you probably got very lucky because even though the bosses didn't have their loot set up properly, the bonus item drops temporarily repair it (but only for the firsst kill in the soft reset).

**Comment by askebv** [comment]
@Heishe I didn't get Blizzard Walkers on first try. I remember it taking a fair amount of time to get those. It might have been the first kill after a soft reset, I don't remember. But it's also possible that you accidentally removed the loot table again ;)
