### ISSUE TITLE
Maps can still be consumed, even if you already have the location

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#298]
As you can see here, I already have Dawn Fortress unlocked. And when I use another map, I still lose the map:

![image](https://i.gyazo.com/7e8fcc3308523c204367d90699b9bd97.gif)

Since you lose the location every time you soft reset, I find this to be a slightly unfair feature.

So I'd suggest either:
1. That the Dawn Fortress raid becomes permanently unlocked when you use the map. After soft resets, it can perhaps be hidden to begin with, and then show up after the first or second raid is unlocked, since that's just about the difficulty of it.
2. Only consume the map if the location isn't currently available.

**Comment by TravisGesslein** [comment]
Phew... had to repair work PC all day. Let's see what issues I can crush before we upload patch later. 

I think I like the first solution more, mostly because there will be raids later which may not be unlocked just through maps. We should have code ready for that kind of stuff. I think it's OK if they are available right from when you unlock the raid mode.

**Comment by askebv** [comment]
@Heishe Then perhaps it should also be an item that you can only loot if you don't have one already and don't have the raid (internally) unlocked. So you shouldn't either be able to loot one if you just did a soft reset and don't have it visible yet.
