### ISSUE TITLE
Losing interest

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#311]
I'm sorry for going here again, but I noticed I really have (lost interest). In the beginning I would open up the game pretty much every day, sometimes even having it running nonstop. Now I only open it up occasionally, out of habit and loyalty to beta testing.

And I wish there was a magical solution, but anything I have in mind would take a long time.

To put it briefly though, I think there's 2 major things missing:
1. More active stuff to engage you while progressing.
2. More milestones/goals.
### 1. More active stuff to engage you while progressing

It can't be mostly waiting for drop luck or gold/exp/AA grinding.

Raids are fun, but are overcome too quickly and too easily. I think there should be a much bigger distance between raids beyond Gardens of Eternity. And I would prefer if they required more planning/strategy/skill to initially overcome. Currently, to defeat a new raid you do two things:
1. Grind levels up to at least 50
2. Equip the equipment dropped from farming the prior raid.

You are also affected by scholar's tower luck, but the hardest part of that is waiting. I remember I suggested a raid planning npc/tool in the alpha days. But most solutions to this will probably be quite work-heavy, unfortunately.

Another active gameplay feature that is easily forgotten, is designing the base. It was actually fun for me at times. However it brings issues and delays to pathfinding (#310) - and is also quite anticlimatic in its progress. At first, it makes a minor difference, then later you can afford to pick between several options. But by the end, you're just paying an increased price for minor increases. It's not bad, but neither the most engaging feature, as is.

I think you could expand that aspect of the game in many fun ways. E.g. having buildings affect each other by which other buildings they are in close range of. Or the ability to upgrade buildings - simply by gold or by gathering materials or intelligence. That's just the tip of the iceberg, but most ideas I can think of are sadly still work-heavy.

The last active gameplay feature I can think of is soft resets. In the beginning they require taking risks (since you don't know if it's a good idea to soft reset when you don't yet have the experience) and every time you do it, it requires at least some minor planning and managing to get back where you were before. They get easier to do over time, it seems. By the end, they're kind of trivial. You'll be back to level 50 in minutes, and you can even clear most raids at pretty low levels. The biggest factor there is gold. Making it cheaper will only make it trivial faster, so instead I think there should be more alternative features to do, or make soft resets even harder, and make the advantages more drastic. That's a hard thing to balance though, and I think it's decent as it already is.
### 2. More milestones/goals

Right now, there's three major measurements of progress:
1. Buildings
2. Raids Completed 
3. Raider Upgrades unlocked

There's also a fourth one, which is number of unique items looted. But there's no way to know if you're missing anything, and it's neither very interesting, since it's mostly based on luck and time.
And a possible fifth one is the arena, but right now it's broken and practically impossible, so there's not much more to say on that.
I don't know how the prophecies or crafting features will work, but I'm guessing they will also be one.

Those major measurements of progress aren't enough to carry the gameplay on for very long. The vast majority of them are completed in a hurry, and simply extending them as is, will probably not bring that much new value to the game.

I don't know if I'm alone with these concerns, but I hope you have a plan for them to be addressed. I've also noticed a big drop in activity here in general, so I'm guessing I'm not entirely alone.

Either way, this is also me explaining why I'll probably be decreasingly active here, unless major stuff changes. If not, I'd probably suggest inviting more beta testers soon, if you want a continuous flow of feedback.

**Comment by DaemoniaV** [comment]
Hi! Agree most part. In #255 already write some suggestion about fill the time before raid beating.
In today reality Raid look so: 
0) Get 50 lvl 
1) Kill one group to loot
Equip and repeat until can kill next group.
What is make game interesting. Some action and reaching some goals. Beat raid is main goal of this game so do it hard)
But there is some problem because You have (so hated by Me) "50-lvl wall". If You just increased damage and hp of boses in Raid it make not good. Let new raid was very hard so You force to think about strategy and seek ways to beat no just 'RUN! KILL IT BEFORE BUFFS END!'
Please take My or Muskar save for example and look into My team. They easy clear all in Auto-Raiding mode. I am ready for new raid - Buff Scrolls are waiting) Test them on new raid and look how it does. May be it is not to late do raid more strong)

**Comment by Ethismos** [comment]
Well, it has to be expected at some point to lose interest. Some core features aren't here yet (like enchantments), there are less instances than alpha, some mistakes would either cause you to stop playing for a day (like my saved games bug) or just hack and make the game to easy, there is no "achievement" like in alpha because... no kongregate to check your reset, best times, highest level etc and most of us played 24/7 to test everything instead of a couple of hours per day which is closer to the average.

I really think that with a few more instances, a reason to afk farm other than exp (enchantments would fix that mostly) and some balance changes to spellbooks this game could keep the average player interested for many weeks or months. Lets not forget that old alpha was, for the old players, a month of reset farming for no reason, then one shot the new raid, then another month of reset farming unless you were doing theorycrafting for best builds so that you can... eh.. reset faster!

**Comment by askebv** [comment]
Yeah. I admit I'm not like the current alpha audience. I don't find pleasure in reset farming forever, if there's nothing special to accomplish. And yeah, I like to play very actively in idle games that engage me. And if we're all doing that, then we're definitely not the average audience, and we might be very off the average person, about our experience.
At times I have been idling a fair amount though - and if full offline progress was implemented, then it might even be similar to the average player.

Since you know the alpha better than me, @Ethismos, then I think your suggestions sound plausible. I'd like to see the enchantment system implemented into this game and see how it changes. Fortunately I still get emails every time someone writes me on this github, so I'll probably get to try it out once it's done.

**Comment by TravisGesslein** [comment]
Thanks for the feedback. 

# More stuff to do

In general, regarding the lack of engaging stuff to do after a while, I feel like that is going to be alleviated a lot (if not completely) once we spend the remaining time until release putting in as many prophecies as we can, filling the crafting system with interesting stuff to create (besides enchantments of course), putting in new events and adding more content like additional mercenary types, cosmetic items, and stuff like that. 

In short, I think once we do that, we will get to a point where the player can check in on the game regularly and always see something that they can or want to do. 

We would have liked to have a lot more of that by now, but we've been busy with bug fixes and minor feature implementations (250 issues!). 

One thing regarding base building: No doubt we can make it more interesting, but I want to be careful not to split the personality of the game in two, if you know what I mean. That's why we are probably going to stay away from more complicated core mechanics extensions to the base building (like the suggested feature of buildings affecting each other and thus players could strategize in how they build their base). 

We want the base building to stay simple, mostly as a way to access new gameplay features, and maybe to have something cute to look at when the player is looking at the game. When we want to introduce more complexity, we would much rather do it in the other parts of the game. Upgrading buildings and stuff like that is certainly a good idea though. 

# Raiding difficulty

I agree that after burning cave and chamber of the sealer in particular raids are too easy right now. We will probably adjust the difficulty of Frozen Coast and Ravaged Abode, but we will definitely work hard to make sure that the difficulty of the raids that will come to the game later is balanced more appropriately to hit the feeling of progression we're looking for. 

We will look into how we can effectively increase the value of strategizing and things like that when it comes to raiding. It's a difficult thing to balance, because we don't want to force players to start having to do arbitrary stuff (like: do a certain build, or activate specific raider upgrades, etc.) in order to beat raids. 

# Fin

Overall, I'd encourage you to try everything out again when we get around to the content mentioned above. I'm positive you'll find the feel of the game greatly improved.

**Comment by DaemoniaV** [comment]
Are You there? May be You write small preview about prophecies?

**Comment by TravisGesslein** [comment]
Yeah still here! Busy with pathfinding and raider movement! 

Preview? For prophecies in particular there's not much to tell. If you know the old questing system, they will work similarly, except that you can do them without having the 'quest', so to speak. The UI will be slightly changed, but overall you will still have the NPC in your town (a scholar who keeps track of all the prophecies you find), you can click on single prophecies to see what you have to do, etc.

There will be two ways to acquire prophecies:
- Automatically, triggered by something in the game. As an example prophecy: "Gain entrance to the Crypt" - "Defeat skeletons in farm map levels [...] and [...] until you find one that has the key to the Crypt", gained after some other completing some other tutorial prophecies. 
- Dropped as items in the forms of prophecy scrolls (as random world drops, or drops from bosses). E.g. an item will drop that is called "Prophecy: Burning Seal", and using this scroll adds the prophecy to your Book of Prophecies, with the same title and a description like "Reignite the Seal by finding three 'Essence of Rage' in the Burning Cave or the Chamber of the Sealer and using the Burned Out Seal in the Chamber of the Sealer". 

Both of those can be done without having the prophecy itself, they are just a guide so players unveil a secret of the Idle Raiders world, so to speak, ingame, without having to look up online wikis or stuff like that. Of course, for those two examples that would make prophecies useless to players who already know the game, but we will also add many new ones.

**Comment by DaemoniaV** [comment]
Thank You for the answer. We are waiting)

**Comment by thorbrian** [comment]
FWIW, I quit playing a week or so ago. I'm still interested in checking in every now and then to see what's new - as you can see :)  but it stopped being worth it to have the browser tab open a couple weeks ago.

For my perspective on things, I think the thing that would get me to play a lot more would be having to make more meaningful choices in raider equipment (i.e. more mutually exclusive but powerful options, like unique items that can equip on anybody, or enough items sets you can't have them all equipped) 

Also, given that one setting can basically idle grind through the entire game, the drop rates and rates you build levels seem way to high for me, relative to the amount of items and the 50 level cap. I'd be very comfortable with making a specific choice to focus on a specific set of equipment I want, and then grinding for a month to finally get just that set.

Right now the non-raid levels really have no meaning that I can tell. I didn't notice any zone specific drops. I think those levels would be much better if I had to make a choice where I was grinding, if they were harder to climb the levels in, and if they had rewards specific to grinding in that area. i.e. like I had to choose between say forest, dungeon, mountains, etc. for idle grinding, each one had it's own unique drops and then the farther I got in that area, the higher the drop rate. So that way when I come back after idling, I have a meaningful choice, i.e. "I've got plenty of heal scrolls, but I need a lot more damage boost scrolls.

**Comment by DaemoniaV** [comment]
1)Did You have any date of nextpatch?
2) How mach time to prophecy and craft release?
3) If I have already done the prophecylike Crypt Key and Burning Seal does they drop and auto mark as done?

**Comment by thorbrian** [comment]
Daemonia, what is the "Crypt Key"? I don't remember having done anything that sounds like that...

... for the burning seal, it looks like it's based on having the items. If you have a burned out seal or a burning seal, you won't have a burned out seal drop anymore.

**Comment by DaemoniaV** [comment]
I get second burned out seal one day ago. And have some Rage dropped before patch) So I can try do second Burning Seal.

**Comment by TravisGesslein** [comment]
@DaemoniaV 

1) Patch 9 will be uploaded today.
2) No idea, but we are now actively working mostly on prophecies and crafting stuff, so hopefully no more than two weeks
3) Yup, should be that way.

**Comment by DaemoniaV** [comment]
Hello. You wrote "so hopefully no more than two weeks". There is two weeks passed. How the progress? Is there new patch date?

**Comment by TravisGesslein** [comment]
I'm currently balancing the next raid (which will be Mountain Refuge, by the way) while @Talisca is creating prophecies for the new Prophecy System. Usually I try to stay away from giving specific dates but I'd say it's looking good for next week. Probably Monday. 

The delay happened because rebalancing Frozen Coast and Ravaged Abode took a bit longer than expected. This is because we've introduced a new awesome thing as part of the crafting system (you'll see once you find your runesmith) and we also added a bunch of rare items that took up some time (not artifact-level, just a decent improvement over the common drops of bosses in Frozen Coast and Ravaged Abode).

**Comment by DaemoniaV** [comment]
Thank You for the answer. Will be wait.

**Comment by TravisGesslein** [comment]
@DaemoniaV 
@Muskar 
@thorbrian 
@Ethismos 

Do you guys know Final Fantasy 12's gambit system? It's similar to our skill priority list feature, except that you can add custom conditions to all of the skills. Stuff like "only execute if target > 10% hp" or something. I just realized that in terms of the gameplay code required, it would be pretty simple for us to add those conditions as well. The by far most complicated thing would be user interface which allows you to change these conditions. 

It would give the player the option to customize all of the skills more to their liking, and it would get rid of a need for AI upgrades like "only execute bulwark if tank has < 30% HP". The conditions could more generically apply to ANY skill, and the player could determine to which.

On a scale of 0 to 10 how interested would you be in something like that? We're pressed for time but I'm thinking about crunching a weekend or something to add it. No promises of course.

**Comment by DaemoniaV** [comment]
Yes. It very familiar. I play FF 12 several hours.
7 of 10
There is more usefull was double setup for execute. For example....
"Execute Mighty Blow if **Rage>90%** or **Target hp<30%**"

**Comment by askebv** [comment]
I don't know it too well - but I heard you describe it before, and have seen my cousin play it for a few hours. But I think it sounds okay. I'll check it out later probably.

**Comment by thorbrian** [comment]
I'm like 7 on the gambit system - I'd try it out for sure - would spend a long time trying to optimize. If I found that certain rules did best in certain circumstances, I'd definitely be really into it.

**Comment by DaemoniaV** [comment]
Can We except new patch today?

**Comment by TravisGesslein** [comment]
Yup, in a couple hours probably. Currently putting on the finishing touches!

**Comment by TravisGesslein** [comment]
I'm cleaning up a bit, so I'm closing this and a couple of other older discussion issues. When release is finally upon us, this tracker will probably get flooded with new and similar issues :P
