### ISSUE TITLE
Some whine...

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#336]
At this point there only one thing in game that sad Me. It is soft reseting... I want to do New Research to upgrade My team but My current lvl 93 and if I do Improving 3 times it give me +30%. But 50 lvl wall break all in pieces. Only at 70+ lvl I have little profit but it need very many time.

**Comment by TravisGesslein** [comment]
Well, that's kind of the point. It's that way in the game to encourage resetting often (instead of just farming to a high raider level and trying to get through raids that way), because the combination of all the new stuff you can get after unlocking (raider upgrades, ancient wisdom, the crafter stuff where you need ancient artifacts) is supposed to be a faster (because its more interesting) way to progress than to just idle for a long time and stay at a high level.

When you feel a little bit of pain for having to reset your hard farmed raider level 93, that's actually kind of what we want to achieve. Players should make a trade-off, because we don't want to make raider level too important, but at the same time it should clearly have value to players.

(Also keep in mind that the cost of the crafter update does not stay the same, it goes up after each upgrade. If you can afford 3x at the current price, most likely you won't get more than 2x after resetting).

Now admittedly this creates the problematic situation such as yours, where someone (for many reasons) idles so long that they get such a high raider level, that resetting the game will for various reasons simply be a net loss (for example, because you already have all important upgrades, etc.). 

I'm not sure how to best fix this, I suspect it will be alleviated when there are simply so many upgrades and stuff in the game that it will take players a long time to get them all, and there will always be a reason to soft-reset. We could also add more reasons to soft-reset in the first place, though I don't have many concrete ideas apart from maybe items that only drop once per soft-reset.

**Comment by DaemoniaV** [comment]
Thank You for the answer. There is some options...
1) New upgrades must be more powerfull than bonus from high level
2) Items dropped once per soft reset - strong but cruel and effective if items was really powerfull
3) Give high level reseted some bonus. For example reduce exp to achieve levels form 50 to X lvl. Where X lvl - max soft reseted by You level. Or give for levels about 50 many ancient artifacts.
4) Remove 50 lvl wall !!!111111 )))))

**Comment by TravisGesslein** [comment]
Closing this as part of cleanup =) Our plan to deal with this at the moment is to (eventually) have a lot of buyable stuff with ancient artifacts. So when you soft-reset, you have multiple sources of raider-improvement to look forward to, instead of just an Ancient Wisdom upgrade like in the old beta. 

Currently, there are ancient wisdom upgrades (and to a lesser extent, raider upgrades, but they are a lot cheaper) and the permanent equipment upgrade from the crafter. With the first post-release patch we will introduce craftable upgraded versions of older set tiers, starting with the first (Might of the Sealer). These are just as powerful as set items usually are, but they can be directly targeted by players, and they require less in total to unlock the full set bonus (though, until  you get artifacts or items from the following raid tier, you'll still want all of them because of how powerful they are). Over time we want to add more and more AA 'sinks' like this, for example when we introduce major gameplay features, it'll probably require AA in some form, too.
