### ISSUE TITLE
Beast Slayer parts...

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#345]
I already have all Golem set but zero Beast Slayer parts. It simple have very low drop %& Or again missimg loot table)

**Comment by TravisGesslein** [comment]
Nope, the loot tables are set up correctly this time. The drop chances for those particular drops are very low, but in return those artifact weapons are always set up such that they are powerful far beyond the raid tier in which they drop 

Since I'm balancing the rest of the raids for re-release right now, I can tell you for example that Burning Seal is still the best warrior 2h weapon around for the raid after Mountain Refuge (excluding other warrior artifacts which we will introduce of course). But the one after THAT will finally see some rare weapons that get better.
