### ISSUE TITLE
Re-release...

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#346]
1) What do You want to make before rerelease?
2) Do You make new raid before rerelease?
3) Do the rerelease on kong wipe our beta progress?
4) Do the testers have some start bonus if wipe?

**Comment by TravisGesslein** [comment]
1) Our primary focus is currently on more content. We have given ourselves an internal deadline (I'd rather not reveal it...) because we're running out of time, and until then we want to put in as much new stuff for the existing gameplay systems as we can. There will be a couple more raids (and we already have raid content lined up for implementation for post-release), a ton more items and prophecies and stuff like that. That's why a lot of the issues in here about suggestions remain untouched, we have to pick our priorities at the moment since we won't get around to implementing both more content and all the feature suggestions (like a DPS meter... etc.). Needless to say we will get around to all of them eventually, most of them post-release though (probably).
2) Not for the beta. Mountain Refuge is the last unfortunately! We will keep updating the beta with bug fix patches (and introduce offline farming and properly balanced arena of course), and those patches may or may not include smaller stuff like new raider upgrades, but no new raids I'm afraid.
3) Nope!
4) No need!

**Comment by DaemoniaV** [comment]
Thx for the answer. Do You think about steam GreenLight somewhere in future?

**Comment by TravisGesslein** [comment]
Most certainly! We'll try to get the game on Steam as a stand-alone application as soon as possible. But it depends a bit on how successful the re-release is. The engine behind the game should allow for a relatively easy port.
