### ISSUE TITLE
Raiders get stuck in town between raids

### ISSUE THREAD

**Issue by Syntastic** [Heishe/idleraiders-second-run#351]
I can't find a pattern to help you here. Sometimes it happens when I manually change modes, sometimes it happens while on Automatic Raiding. Entering then exiting a farm map fixes it. I did destroy 2 of the road tiles to test the destroy button, don't know if this is the cause

![screenshot_4](https://cloud.githubusercontent.com/assets/6775313/19708847/4edd0938-9ae7-11e6-9ca6-add1abec042b.png)

![screenshot_5](https://cloud.githubusercontent.com/assets/6775313/19708849/52bcbec2-9ae7-11e6-9173-ffd630f8e7cf.png)

**Comment by Syntastic** [comment]
![screenshot_10](https://cloud.githubusercontent.com/assets/6775313/19710882/2cd5ece6-9af7-11e6-9194-4c8058efff3d.png)

beginning to see a trend here..

**Comment by Syntastic** [comment]
![screenshot_11](https://cloud.githubusercontent.com/assets/6775313/19711909/e9a10106-9afe-11e6-81a5-332d1dd1eee8.png)

![screenshot_12](https://cloud.githubusercontent.com/assets/6775313/19711912/edb485ce-9afe-11e6-8c8d-059a085cfa2b.png)

**Comment by TravisGesslein** [comment]
Thanks for the detailed report. The common pattern is actually the red priestesses standing next to all the stuck raiders. This one took a while to fix. Initially, during debugging, it looked like this was simple physics bug where raiders collided with walls that weren't there. But this wasn't the case. 

Our combat system has a small piece of code where, whenever an entity is attacked and has itself no current combat target, then its combat target is set to whatever it was attacked by. This is basically there so that when you attack a monster, it immediately aggros onto the attacker, instead of continuing to chill while its bombarded with arrows. 

When raiders arrive in the base with low HP, the priestesses will immediately come rushing for them to heal them. One quirk of our combat system is that healing is just implemented as negative damage. There's no gameplay reason for this, it just turned out that all the code for healing and damage looked basically the same, so we unified the systems and just turned the damage sign around for healing. However, this also has the unintended consequence that healed raiders will immediately set red priestesses as their combat target because they are being attacked by them with negative damage. 

This would be mostly harmless - when the current combat target is friendly but you have no abilities to use on it (such as heals), the raider will just pick something else as soon as something better becomes available. However, in this particular case, players had the 'stay at range' upgrade enabled. This causes ranged raiders to try and flee from the horde of red priestess who are coming to heal them. 

But when the priestesses stand between the raider and their movement target (the map exit, because it wants to get to another map), the raider gets conflicting information about what to do (''run away" + "go to target") and is seemingly stuck. In fact it's stuck in an endless loop of alternately going left and right - this is sometimes visible as wobbling. If this happens fast enough or the directions where the raider wants to go are exactly opposite, it's not visible at all and it looks like the raider is just standing still.

Anyways, the bug should be fixed in the upcoming patch!

**Comment by Syntastic** [comment]
Thank you for the detailed explanation. Knowing more about the game mechanics will definitely help with testing!
