### ISSUE TITLE
Immortal raider buff

### ISSUE THREAD

**Issue by isNaN6** [Heishe/idleraiders-second-run#365]
Hi again.

On the last boss of Tomb of the Pharao, a debuff is placed on a tank.

Don't think the label is correct : 
![17ef2a589b8a42d0abccd452729b3e47](https://cloud.githubusercontent.com/assets/23148644/19849447/aee9a7f8-9f53-11e6-9b57-da76e191b649.png)

This boss is also... quiet hard? (Bugged?) I can't even make her health drop.
edit: small victory, dropped her to 1.1M/1.2M health

**Comment by TravisGesslein** [comment]
I'll investigate the buff, it's supposed to make them immortal for a while (instead of taking damage, which happens when the Pharaoh doesn't find your heart to be pure).

Regarding boss difficulty: If the buff above is bugged it makes the boss quite a bit harder of course, but the fight seems to work fine otherwise, from what I can tell.

**Comment by TravisGesslein** [comment]
Yeah, the description was wrong, but the buff itself should work correctly. Will be fixed in upcoming patch.
