### ISSUE TITLE
Fireball 100% crit chance still has chance not to crit

### ISSUE THREAD

**Issue by dcish** [Heishe/idleraiders-second-run#376]
Currently have 98.6% crit chance on fireball from gear and 8% chance from the skill book equipped. Sometimes it still doesn't crit. In theory with inner combustion it should allow me to chain cast fireballs every second, but right now it's sometimes getting a reset.

**Comment by TravisGesslein** [comment]
In the training facility I can't seem to reproduce this. Just some checks:
- By reset you mean, the mage has to wait for the entire cooldown to end before casting again? It may appear that one or sometimtes two seconds cool down before the mage casts again, because the fireball itself arrives some time after the skill was triggered, and the skill itself has an execution time during which the mage can't do anything.
- Are any of the skillbooks used Level 2 or 3?
- Actually, savegame once again would be helpful. I tested with the one you sent yesterday, but the problem doesn't seem to occur there.

**Comment by dcish** [comment]
Sure I'll send a version of it when I get home.

**Comment by dcish** [comment]
I changed my gear to 100% and saw it have a full 15s cooldown today, ill send you a backup.

**Comment by TravisGesslein** [comment]
Hi, thank you, the savegame would be very helpful.

**Comment by dcish** [comment]
I think this happens if the mage casts the fireball but the enemy dies before the fireball actually lands (if that is how it's calculated). It's really easy for me to see it because my mages are always mana empty farming when with 100% crit chance, they should always be -45 mana maximum.

One fix could be remove mana on fireball hitting instead of on fireball animation casting.

**Comment by TravisGesslein** [comment]
Yeah, this is probably what happens. The damage an ability does, whether or not it crits, the bonus damage from all the various sources of bonuses in the game, etc., are applied when the projectile actually hits. 

There's no big technical reason for it, it's just a design choice. For example we want buffs that were triggered while the projectile was in-flight to count. Also, some abilities that do damage can crit multiple times (for example, the multiple shots passive that fires three projectiles), and we wanted to allow some hits to crit while others do not (so that it feels really awesome when you get lucky and all of them crit).

That's just an explanation of what's going on. I think we can somehow work around the issue by detecting whether the ability would crit or not even if the target mob is dead.
