### ISSUE TITLE
Boss stops attacking

### ISSUE THREAD

**Issue by dcish** [Heishe/idleraiders-second-run#379]
Beholder in lair of the seer stops attacking after breath. Unsure how to reproduce, assume its a pathing issue. The main tank is not taking any damage but can't get healed either. Blew him right off the screen!

**Comment by isNaN6** [comment]
Had my main tank also blown out of the screen, he is just in some black part of the map where all i see is black.
In my case the boss didn't stop attacking because my other tank took the aggro.

**Comment by TravisGesslein** [comment]
Yeah, if the targeted raider goes somewhere where the boss can't find a path to, it will look like the boss just stops attacking. Will fix.

**Comment by TravisGesslein** [comment]
Been trying to reproduce this for a while now. With certain configurations I can see how the boss itself gets pushed to the right (probably because of the zombies from the Undying set), but the Warriors only get pushed slightly to the left, never with enough speed to tunnel through collision tiles or something like that.

Could you give me more information on how this happened? Where do the Warriors get stuck? On the left side of the boss platform? Or do they somehow and up on the right side of the boss and then get pushed to the right side of the room? By any chance, do they end up on the far right of the screen, maybe 3-4 (invisible) tiles away from the boss platform?

**Comment by TravisGesslein** [comment]
As a kind of band-aid, with the next patch we'll add a check to see if entities have gone off-map for some reason (this shouldn't ever happen, but apparently it does! :hankey:) and if so, teleport them back to the entrance of the map. 

This isn't a fix to why this occurs at all, of course, but it should prevent larger gameplay issues from occuring. For example, currently if this happens it's possible to get stuck on this raid in auto-raid mode for up to an hour, because one of your raiders goes off-map, but since they never die, the raid doesn't end.

**Comment by isNaN6** [comment]
Hi,

Had this happening to me several times.
Once, my warrior was on the right of the boss and got pushed back hard. I think (not sure on this) that when he does is breath, if an hero as a stun, he gets pushed way back since he isn't auto advancing at the same time. He flew past the right border of the map and if I selected him all I could see is a black screen (under the map?)

Another time, it happened to both my tank warriors on the same fight. they where tanking the boss on the stairs. When the boss did is breath, the just directly went under the map.

Hope that helps.
