### ISSUE TITLE
Inventory icons don't show up

### ISSUE THREAD

**Issue by dcish** [Heishe/idleraiders-second-run#384]
Don't know how to produce this, but sometimes on equipping skills and swapping tabs in inventory the icons won't show up in the background. A refresh fixes it. Not very common to have happen but has happened at least twice.

**Comment by Profputricide** [comment]
I can reproduce this by disabling classes in the inventory and then switching equipment snapshots. Not sure if it's the same issue, but it might help

**Comment by TravisGesslein** [comment]
The way the class filters work has been changed with upcoming patch, because just removing the (un-) filtered class items from the inventory created a lot of problems when players switched snapshots, tried to reorder items without activating class filters again, and some technical problems were caused, too. So this shouldn't happen anymore :)
