### ISSUE TITLE
Trigger skills

### ISSUE THREAD

**Issue by Profputricide** [Heishe/idleraiders-second-run#387]
Never seen time pressure, multishot or cleave work on killing blows. So i'm assuming trigger skills don't work on killing blows?
This is for 1 hit kill monsters at least, didn't really test it at harder monsters.

**Comment by TravisGesslein** [comment]
They should work if the raider with the trigger skill in question does the actual killing blow. But if, for example, another raider does the actual killing blow, and an Archer's arrow arrives just after the monster already died, nothing triggers because that only happens when the raider actually does damage. This is (probably) fixable however. I had to introduce a similar work around in the code for the on-crit effect of Fireball+Combustion. 

Will probably delay this to Patch 16 however, Patch 15 is already a couple days overdue, and I hope we can apply it some time today.

**Comment by Profputricide** [comment]
Been farming for quite some time on map 3 with mages out of mana, warriors only have cleaves and archers only rain of arrow and time pressure or rain of arrow and multishot.
Would expect to have seen at least 1 of the skills trigger as theres not many other raiders getting killing blows. Multishot/cleave might be hard to spot, so i could've missed it (but i don't think so).
Time pressure has an obvious visual effect, and have never seen that either even with 3 time pressures on both archers.

**Comment by Profputricide** [comment]
Add the Arcane Barrage skill to this list aswell, the cooldown on missiles don't reset if the mage never hits a target with the cast.

**Comment by Profputricide** [comment]
Just noticed that my warriors stopped cleaving in map 34 as soon as they were able to onehit kill monsters with an autoattack, When i remove items to have them do less than 5126 damage per autoattack they cleave again (it works fine if the trigger skill increases damage enough to oneshot the monster)

Just confirming what i initially reported.

**Comment by TravisGesslein** [comment]
Somewhat overdue, but there does indeed appear to be a bug in the combat code that prevents killing blows from triggering passives properly, even after all the changes made since then. Fixed internally, will be available in one of the future patches.
