### ISSUE TITLE
raids not advancing.

### ISSUE THREAD

**Issue by dcish** [Heishe/idleraiders-second-run#390]
Patch 15, did crypt and throne room but the next raid is not appearing as an option to complete.

During crypt, after boss died, my characters idled at the entrance dancing around for a few minutes before i had to manually move them out

**Comment by ImperialUser** [comment]
More info: It looks like the boss death does not trigger.  The raid timer starts counting down after skele death, but no loot, no opening of next raid, and raiders walk out like in farm maps when you kill everything on the map.

**Comment by TravisGesslein** [comment]
Yup, thanks for the bug report. Fixed this internally. I want to fix an issue that was reported since Patch 15 where priests bug out (I think this may be unrelated to the bug where Prayer prevents them from doing anything, but not sure), but lacking savegames make this hard to track down. Either way by this evening the issue will be fixed. Sorry it happened.

**Comment by TravisGesslein** [comment]
(The fix-patch was uploaded last week).
