### ISSUE TITLE
Suggestion for snapshots

### ISSUE THREAD

**Issue by Profputricide** [Heishe/idleraiders-second-run#391]
When refreshing the game, the snapshots sometimes swap places. 
So i'd suggest to add icons to make it easier to remember which one is which. 

Also the list of items doesn't really help ... it's only pushing the snapshot name out of my screen, making it even harder to find out which one is which. 
For this i'd suggest having names at the bottom, or not having the list of items show up.

**Comment by Profputricide** [comment]
Would also like to add to this, that 90% of the snapshots is about skillswapping, and that keeping them up to date is a real pain if you get a new piece of equipment.

**Comment by TravisGesslein** [comment]
Yup, the snapshots are a bit messy. We can make the tooltips a lot smaller by showing item icons instead of listing all the names. I like the other suggestions too, will probably implement all of those once we make the snapshot code more robust.

Regarding the second comment: Yeah it would probably make sense to have separate skill and equipment snapshots. Equipment is transient by nature in this game, so I'm not sure if it even makes sense to include that in snapshots at all.

**Comment by Profputricide** [comment]
Different equipment setups can be usefull when you switch between farming and raiding, but not as important as skills. (blizzard set is a good example of something you want to have when farming low level zones, but is not as important in raids)

What i would love to see though, is raiders automaticly swapping to a raiding and farming setup when they are set on the raid+farm mode.

**Comment by TravisGesslein** [comment]
I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
