### ISSUE TITLE
Suggestion for raider upgrade

### ISSUE THREAD

**Issue by Profputricide** [Heishe/idleraiders-second-run#392]
I really dislike to see my raiders activate buffs/debuffs that are still active, and thus wasting their resources

Maybe have an upgrade that makes them wait untill buffs/debuffs are over before using it again (somewhat similar to bulwark upgrade)

**Comment by TravisGesslein** [comment]
Yeah, we're not sure how to solve this yet. We want to enable more skill customization in the skill priority list interface, such that you can say stuff like "only execute this if the buff isn't already active" or "only execute if enemy has > 50% health" and stuff like that. We'd rather not spend valuable development time on smaller upgrades that essentially fill the same purpose until then.

However, this is one of those things that keep getting pushed back further and further because of other stuff we have to do first, so maybe we'll have to introduce those kinds of raider upgrades after all, because they take less time individually and are easier to squeeze in than a larger upgrade like an almost FFX12 gambit-like system.

**Comment by TravisGesslein** [comment]
I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
