### ISSUE TITLE
Some feature request

### ISSUE THREAD

**Issue by roflaa** [Heishe/idleraiders-second-run#397]
- Having a follow camera available which is always putting the selected raider into the center of the screen. this could be done by having a small button near the the raider picture
- get information on how often a raid has been successfuly be done.
- as the cash flow is very low give the possibilty to sell stuff from raids.

**Comment by Profputricide** [comment]
- A follow camera is already available (alt+f), it's not focussing on a specific raider tho.
- Number of clears doesn't sound important to me, but extra info is nice i guess.
- Don't think there will be selling because of the runesmith extracting items (would rather see more use for the materials in game instead)

**Comment by TravisGesslein** [comment]
The second suggestion can be added relatively easily. I like the first one, too, but that's a bit more work. I will add a post it note to our wall for it. 

Regarding number 3, cash flow is a bit tight in the beginning (it's a common complaint), but that's intended. Do you know the saying that a trade wasn't fair unless both parties feel cheated? That's kind of the feeling I'm going for. I want gold to feel valuable enough that you feel like everything is a tiny bit too expensive. And at the same time I want you to feel like spending that little bit too much gold is totally worth it because of what you get for it.

Making stuff cheaper or giving more ways to get gold undoubtedly makes it more convenient to get the stuff you're going after, but it inevitably also reduces the 'value feel' of gold. 

After a certain point it also seems like players have too much gold in general and there aren't enough 'gold sinks' that make gold feel valuable again. This is something we want to improve, we have some concrete plans for the first major patch after we release the game to everyone.

I should also note that, if you haven't unlocked the crafting system yet, you should wait until you do, because you'll discover another good use for raid items you don't need 👍

**Comment by roflaa** [comment]
Thanks for you answers guys. I understand the intend of the money system and i already have the crafting system unlocked :) But also with this i have so much material for crafting but i always lack in money. I always have to save money for buying wisdom. maybe you could a ancient wisdom which makes the buying of additional wisdoms cheaper.

one more thing which would be great is a combat log. to see which spell books work out in which mechanic. even this is only available in the training ground.

**Comment by TravisGesslein** [comment]
I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
