### ISSUE TITLE
Some Skillbook level 3

### ISSUE THREAD

**Issue by Plop86** [Heishe/idleraiders-second-run#398]
So i beaten the current content, and the shop is selling all usual spellbook level 3 but fireball level 3 is it intended?
Focused shot level 3 i also never seen dropping from maps like level 2 did.

**Comment by TravisGesslein** [comment]
Fireball lacks a level 3 skillbook right now, will add.

**Comment by TravisGesslein** [comment]
Also, Focused Shot level 2 dropping from farm maps is more of an exception than a rule. Most skillbooks don't drop from random mobs. We added that (and a couple of other skillbooks) to the global drop table early in development when it was relatively empty, just to have something in there. We didn't remove it after we added a lot more items because we thought it wouldn't hurt to leave it in there. Now I'm not so sure because it's probably confusing to players and they expect skillbooks of all levels to drop everywhere...
