### ISSUE TITLE
Can't access second run

### ISSUE THREAD

**Issue by Exili** [Heishe/idleraiders-second-run#406]
I was reading that you had to be a Kong+ member to get into beta I purchased Kong+ to enter it but it says its still only able to be played by K+ members did I do something wrong?

**Comment by TravisGesslein** [comment]
We ourselves can't do anything about it, I think (we have no way to invite people, as far as I'm aware). Can you contact Kongregate support for this? I'm sure they will be glad to help in that case, especially if you purchased Kong+ for this game specifically. 

There was another player on the forums who purchased Kong+ after the beta already started, and had no problems with getting access to the game. So that should work in general, not sure what went wrong for you, sorry!

**Comment by Exili** [comment]
I figured it out I was using the wrong address to get to it since I couldn't search for it even with K+ I had to use a screen shot from another user to try to figure out the address to play. Forgot -preview on the end of it simple mistake.
