### ISSUE TITLE
Disarm vrs bosses

### ISSUE THREAD

**Issue by ImperialUser** [Heishe/idleraiders-second-run#408]
My Warrior with Disarm will stop attacking the current boss and run ahead to the next boss to inflict disarm on it.

**Comment by TravisGesslein** [comment]
Hi, thanks for the bug report. Also sorry for the delayed answer. I'm working on some code internals that will allow us much more robust reproduction of when things go wrong, and that's turned out to be quite a bit more work than originally anticipated. 

The bug you mentioned has been fixed internally and will be fixed in the live version of the game when the next patch is uploaded :)
