### ISSUE TITLE
Suggestion for the new Mage class

### ISSUE THREAD

**Issue by Drakenfeld** [Heishe/idleraiders-second-run#41]
Give the mage a basic attack!!!, since all they do is stand around when they don't have mana... but even so 15 second cooldown doing nothing while in them 15 seconds of doing nothing Warriors stack up more damage.

Maybe add an basic physically attack to priests again aswell.

**Comment by askebv** [comment]
I'm not sure I agree. The good thing about mages is their ability to burst (a lot of damage in short time) - which is important on self-healing enemies. And later on, I'm sure all classes will be so busy that a weak attack would be a waste of a "turn". But the skill priority system might make it alright.

The biggest gain from your suggestion, that I can think of, is the ability to farm low level maps much faster - and I'm not sure low level farming needs a boost. It's already the fastest way to farm gold by far, which would make high level farming that much worse.

**Comment by TravisGesslein** [comment]
Our original design intention with the class fits exactly what @Muskar says. It's supposed to be a burster with high cooldown skills and high mana costs (to varying degrees, frost mages will be an exception). Also what's cool about this is that late game mages look a lot more powerful than early game mages (as opposed to just doing more or less the same thing with higher numbers) because they have higher mana pools (or higher crit chance which benefits fireball builds). 

On the other hand this exact issue has been raised by Alex before (our artist). He felt that mages looked kind of lame when they bursted a couple of times and then just stood around doing nothing. I'd like to get the best of both worlds, but I'm unsure what the best way to implement it is. If it's just a visual issue, we could give mages some kind of very weak default attack, or we could introduce a casting time for all the mage skills, so mages don't just stand around doing nothing, and instead spend the time actively casting.

**Comment by askebv** [comment]
Since you're borrowing a lot of mechanics from WoW, you could make a wand type-of-thing that just throws a tiny magical particle every once in a while.

And if you want an alternative to this "weak attack" doing damage, you could make it steal/generate a small amount of mana every time it hit an enemy. It'd require some rebalancing of course - but that way it would at least not feel like idling.

**Comment by Drakenfeld** [comment]
I see your point now that I've got magic missiles + 2 Arcane bombardment + Arcane barrage + mana potions, just wipes the floor with most bosses :-p

maybe you could add some cool visual effect to the mages when they aren't doing anything, like adding a table they can sit at and have _Cup of Tea_ while they wait for the cooldown!

**Comment by TravisGesslein** [comment]
I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
