### ISSUE TITLE
healers + farming moddification suggestion

### ISSUE THREAD

**Issue by ImperialUser** [Heishe/idleraiders-second-run#425]
Healers don't heal in base if farming is active, but they will if you switch from farming to rest.  This is most noticeable at later levels when characters have 10k+ hp each with group farming active.  It's getting to a point where leveling is slowing down farming gold.

2 suggestions:

1) Obviously, have priests heal when in base.

2) Increase healing of red priests depending on your level.

**Comment by TravisGesslein** [comment]
Next patch will have both! Priestesses already scale with your raider level, but the scaling is a bit out of whack with the basic HP scaling of raiders after level 50 (because each level after 50 provides 4x the bonus that levels before that used to give), so we're quadrupling the damage/healing output of priestesses at later levels.

Also, priests not healing in base during farm mode was a bug!
