### ISSUE TITLE
Servers offline?

### ISSUE THREAD

**Issue by Profputricide** [Heishe/idleraiders-second-run#429]
It looks like cloud servers are offline or something, saves aren't showing up and on opening a local save it couldn't acces snapshots stored in the cloud.

**Comment by Profputricide** [comment]
@Heishe still waiting for an answer, many people are unable to play right now!

**Comment by TravisGesslein** [comment]
Sorry! Looking into it.

**Comment by jmweaver** [comment]
Same issue here, lost access to my cloud saves.  (in case it isn't a wholesale server drop)

**Comment by TravisGesslein** [comment]
Sorry, I wasn't able to reply to the issue earlier because github was down. Our server provider (the people we rent our servers from) has had a lot of issues on their side today, and my current understanding is that they're still working on fixing it. From personal tests it seems server responses take a long time or timeout from time to time, but work fine at other times, so to access your cloud saves the best strategy is probably just to retry regularly.

We'll switch server providers for release. We've had quite a few issues with these since we started running our servers with the current one.

**Comment by hyro77** [comment]
Seems servers are offline again?
already wrote you a mail (user hyronimus)

**Comment by TravisGesslein** [comment]
Hello, 

this time the server's weren't offline. Our web dev investigated the problem and there was a simple issue with security certificates on our servers... they ran out. We renewed them and saving/logging in etc. should work fine again.
