### ISSUE TITLE
Release date?

### ISSUE THREAD

**Issue by DaemoniaV** [Heishe/idleraiders-second-run#439]
Hi. Did You have any release date at this point?

**Comment by TravisGesslein** [comment]
We have a decent idea regarding release internally, but not announced any specific dates yet (because we're not 100% sure at this point, we need to work together with Kongregate staff to determine an exact date). 

What I can tell you is that it's fairly close. Next week (probably on Wednesday), we will have the kongregate beta servers down for maintenance, because we're switching our server architecture over to the new system that is going to be used for release. The primary purpose is, of course, to test that architecture for release, because it's the only major hurdle preventing us from releasing the game!
