### ISSUE TITLE
Suggestion: partial wisdom gain

### ISSUE THREAD

**Issue by ImperialUser** [Heishe/idleraiders-second-run#448]
I normally go to bed, set raiders on auto-progress and wake up where they get stuck and have a decent amount of AA waiting to be collected.  Well I did that and apparently I'm stronger then the average bear because now I have 2m AA waiting. It's going to take me over a month of idling for gold before I can collect and start progressing.

It would be nice if we could do a partial AA gain of some kind.  Like "you have enough gold to collect X AA, but if you do the rest will be lost" kind of thing.

(added)
Never mind, for some reason I thought it would take 200m not 20m to collect it.  But my suggestion still holds.

**Comment by TravisGesslein** [comment]
I'm still thinking about this quite a bit. The classical system of how resets work compared to other idlers is probably not optimal for Idle Raiders because of its differences to other idle games.

I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
