### ISSUE TITLE
Suggestion: multiply all damage and HP values by 10

### ISSUE THREAD

**Issue by midgetmafia** [Heishe/idleraiders-second-run#475]
Many buildings and skills increase or decrease damage by a very small percentage, in the 1-3% range.  However, base HP and damage values are so low that these increases can often be lost to rounding.  Increasing the base damage and HP values would allow such % increases to always provide at least 1 point of actual improvement.

**Comment by TravisGesslein** [comment]
All those decimal points are usually fully used in the combat system. For example, if you check your raider stats, it should show two decimal points for their damage. But please let me know if you find cases where this doesn't apply, so we can fix it.

Also it would be intuitive to have values fully based around having 1 be the smallest unit, but it's really hard to implement in practice. For example, even if we multiplied everything by 10, your raider had 750 damage instead of 75, a 3% increase would mean +22.5 damage and you would end up with the same problem.

**Comment by TravisGesslein** [comment]
I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
