### ISSUE TITLE
Stay At Range and Avoid Area of Effect Damage

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#48]
I'm not sure what this behavior is supposed to be, but I have "Stay At Range" and "Avoid Area of Effect Damage" enabled and this is how they behave:

![image](https://i.gyazo.com/c0db61837574abfb7a93678d60e4d9df.gif)
![image](https://i.gyazo.com/556447d0824d107f6c0a67c5ffdccc00.gif)

Most notably is that they're glitching backwards over time, and then walking forward for half a second.

**Comment by TravisGesslein** [comment]
Thank you, we'll investigate it.

**Comment by askebv** [comment]
I tested some more and don't see any effect of the "Avoid Area of Effect" upgrade. What is it intended to do?

The glitching thing is definitely the Stay Out of Range upgrade.

**Comment by TravisGesslein** [comment]
It makes raiders walk away from AOE dot attacks like the like the lava bomb from "fireal" in Burning Cave, or the fire things which the old fire elemental in Mountain Refuge spawned. Some AOE attacks aren't included, like the dragon's fire breath.

**Comment by askebv** [comment]
Yeah, I since saw its effects. It's not super effective but it does make a tiny difference I suppose. In reality they're not really avoiding it - they're just sneaking slowly out of the area. Often they'll take over 20 seconds to get out of a small AoE area, and by then, it might even be gone.

Are they intended to move that slowly? And will we later be able to get "learned raiders" that have experienced a raid so many times that they will avoid the AoE as soon as they see the trigger - like semi-experienced MMORPG players would?

I'm assuming full-on-strategy anticipation (like spreading out for bosses that do on-target AoE effects) are long down the list of would-be-nice-to-have.

**Comment by TravisGesslein** [comment]
I haven't looked at it since the last time I tried it, it's possible there might just be a movement bug when they walk out of the AOE. They aren't supposed to be any slower than their normal movement speed (but not faster either). 

The suggestions after sound exciting. We've had ideas like that written down somewhere on our to-do lists, but yeah, pretty far down, mostly because it's technically probably a pretty challenging problem. Large overhauls or extensions to raider behavior, making them learn stuff etc. is something we will look at after the game is re-released, when we decide which new features to add, etc.

**Comment by askebv** [comment]
@Heishe Well, they're not anywhere near walking speed. In fact, they're slower than in the above animations.

It seems like their attack move is conflicting with it. Because they seem to avoid at intended speed when they're already walking (towards a boss).
