### ISSUE TITLE
Filter Problem

### ISSUE THREAD

**Issue by vthrenee** [Heishe/idleraiders-second-run#496]
Hello!
Sometimes when you filter the items and you select "None" or "Usables first" the item selected disapears.
(probably when you click those options you also click on the trash can on the background)

First pic:
https://gyazo.com/a3e3e721d5c75fe0b80232947bb0f619

After selecting "Usables First":
https://gyazo.com/81f228d1dab9d19e394796ff52f21f38

**Comment by TravisGesslein** [comment]
Yup, will fix this.

**Comment by TravisGesslein** [comment]
Fixed next patch. This happens because the delete button gets clicked underneath the menu when you use those sort types. The 'tech' (almost too grandiose a term for that) behind those dropdown (or rather dropup in the case of that inventory) menus is pretty old and has a lot of hard to fix bugs. I've done a dirty thing and fixed it by swapping the order of the trash bin button and the sort button so it's impossible for the menu items and the trash bin button to overlap!
