### ISSUE TITLE
No WAIR and other enchantments.

### ISSUE THREAD

**Issue by Dannyyp** [Heishe/idleraiders-second-run#545]
I've cleared up to the Yetis and farmed to level 27 and WEIR and other enchantments have never appeared in the runesmith. I've tried removing it and re adding it and nothing has changed. The three things that are available are Quickness, Blessing and the skillbook Sacred Rite.

Please help me fix this.

**Comment by Dannyyp** [comment]
Seems the latest patch has forced it to appear after a reload

**Comment by TravisGesslein** [comment]
It's possible that they simply showed up as invisible because something with their graphics was corrupted. This can happen when a new patch comes out, your browser updates to the newest 'code', but all the assets used are cached locally. 

The easiest fix is to force your browser not to cache that stuff by opening the dev console (f12 on most browsers), enabling the option there to disable cache while its open, and refresh the page like that. There's ctrl+R and shift+R on most browsers to force a reload, but it seems this doesn't work in all cases, as players have reported those problems even while using those combinations!

**Comment by TravisGesslein** [comment]
Leaving this open for a little while in case somebody else experiences the same problem.
