### ISSUE TITLE
Beat the golems and still get t5 global drops

### ISSUE THREAD

**Issue by Falopi** [Heishe/idleraiders-second-run#568]
I cleared the golems out a couple days ago and after over night farming I still only get t5 gear drops, I was told I would get t6 global drops after beating the golems to help clear the undying castle. Now i'm stuck trying to kill the vampire with lower t5 gear because it's all I can get. Is there something wrong with my save?

[error_report (2).txt](https://github.com/Heishe/idleraiders-second-run/files/855617/error_report.2.txt)

**Comment by Falopi** [comment]
after killing the zombie in the undying castle i did a soft reset and went to grinding up levels/global drops. I'm now getting only t1 global drops.... something is wrong here hope it can be fixed soon this stinks

**Comment by TravisGesslein** [comment]
A lot of players want to grind out specific drops from earlier tiers than the ones they've already progressed to (this includes players who buy loot chests). Since capping the loot to tiers you've already beaten locks you out from earlier drops forever, we left it at the current system (where you have to get back to the tier by beating the respective raid(s) before those tiers start dropping again) until we can implemented a better way for players to target gear from previous tiers!

**Comment by Falopi** [comment]
good to know! Thank you for the response :D
