### ISSUE TITLE
Cloud save after patch not working

### ISSUE THREAD

**Issue by mccl0215** [Heishe/idleraiders-second-run#574]
After the latest patch the cloud is no longer saving. It says that I am not connected to Kongregate. I try to push the button and nothing happens. I am signed in to Kongregate through Chrome as normal.

**Comment by TravisGesslein** [comment]
Sorry, we're currently investigating all these cloud based errors.

edit: Just woke up, and getting up to speed with server dev. The servers have been taken offline because it seems like we're being DDOSed. Even now, with the API completely offline, the load on our servers is very high. Some players really didn't like the patch...

**Comment by TravisGesslein** [comment]
Closing this for now as we seem to be getting a grip on it. The attack hasn't stopped but we've made some optimizations to our server side stuff which means we can just take the hit at the moment, basically.
