### ISSUE TITLE
Bought Loot Chests and got nothing

### ISSUE THREAD

**Issue by Redvenomxz** [Heishe/idleraiders-second-run#579]
Had some kreds so i decided to buy 2 loot chests and i got absolutely nothing from them, name on Kongregate is Peewee872.

**Comment by TravisGesslein** [comment]
Hi,
we're still dealing with DDOS stuff on the servers. If the purchase went through it'll be stored on our servers correctly and should show up once your client is able to reach them. Reloading the game from time to time should work.

Sorry for any inconvenience caused.

**Comment by TravisGesslein** [comment]
Looked into database and your purchase is there by the way!

**Comment by Redvenomxz** [comment]
where would it be i dont see it anywhere

**Comment by TravisGesslein** [comment]
The cones and/or loot chests should show up once your client can reach the servers again. For the most part that should happen automatically, so checking the shop from time should work. However restarting the game (by reloading the page) is a sure way to make them show up immediately if you know you can reach the servers (for example because cloud saves work and there's no disconnect icon).

**Comment by TravisGesslein** [comment]
I assume you were able to solve this? Closing this for now.
