### ISSUE TITLE
Save game gone

### ISSUE THREAD

**Issue by gorgtallisman** [Heishe/idleraiders-second-run#598]
went to do a export of my game file and now when i refreshed my save game is gone im back to day 1

**Comment by gorgtallisman** [comment]
You have lost a paying customer.It has been over 8 days that I've tried to contact you about my save file being deleted and no reply or any kind of help offered. The game is decent but you have EPIC  FAILED at basic customer service.

**Comment by TravisGesslein** [comment]
Hi, sorry about the delay. Ou basic customer support is weak because all of that is done by our actual developers (of which there are only 3 currently), so requests can go unanswered for a long time when we're particularly busy with something important (in this case, 1.1 and various server side developments).

Also regarding lost saves, please contact us at social_at_pitforest.de

**Comment by gorgtallisman** [comment]
Lame reasons for having poor service, when you have such a major bug that save games get wiped you need to stop worrying about your update FIX the major bug and then fix the problems the bug caused in this case SEVERAL peoples save games deleted. im not worried about the save game anymore 9 days has passed of lost time and play. I have allrdy started a new game and TOOK what i wanted without paying a dime.
