### ISSUE TITLE
Enrage debuff bug

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#63]
My warrior kept his warrior enrage size buff after the buff ended. It could be because he died before the duration ended .

He now runs around like this:
http://imgur.com/ItsyPWC
http://imgur.com/36n3Twz

When enrage procs again he becomes even bigger!

Edit: Happened again and i don't think he died... could it be that it appplies more than once somehow?

http://imgur.com/kQLQ8F9

**Comment by askebv** [comment]
I have a suspicion that it happens when it triggers in The Crypt. I'll try to check for it when I can.

EDIT: Scratch that. Happened without being in The Crypt. I think it has to do with viewing another map than the one your raiders are on, when they enrage. Or perhaps it's when he dies with enrage.

I was viewing the Frozen Coast raid that they had died on, while auto-raiding. And I checked the farm map that they had now gone to, and he was suddenly huge. All the times it has happened, has been while I have been on another tab though, so I don't have good enough data yet.

**Comment by TravisGesslein** [comment]
I'm locking this as duplicate and will leave the later one up since it contains more correspondence.
