### ISSUE TITLE
T9 Set bug(s?)

### ISSUE THREAD

**Issue by dudehey3811** [Heishe/idleraiders-second-run#631]
T9 apparently crashes anyone who enters the practice arena with the bonus active, also there have been reports of the set breaking magic missile just by casting, as well.

**Comment by vd2b** [comment]
With T9 set / 3 bombardments/barrage combination happens unlimited increase in damage per second (at combat meter) and amount of missiles that are launched per second (visually on screen). While we should have a fixed dps and speed with this setup.
Update: can not reproduce unlimited dps increase anymore.

**Comment by hamburml** [comment]
Thanks for your report.

I was unable to recreate the crash when the practice arena is entered with an active T9 bonus @dudehey3811 . I also can't reproduce an unlimited dps increase @vd2b.

What exactly did you use to get this errors? What browser do you use?

**Comment by vd2b** [comment]
Minimal example of error is T9 set bonus + Arcane Barrage as mage ability. 
Crash occurs due to performance issue (starts from 100% CPU used and then game freezes) and happens when I use 3 Arcane Bombardments + Arcane Barrage abilities on both mages.

I am using Firefox browser version "54.0.1 (32-bit)".

'Unlimited increase' was most probably my estimation error. Time needed to get to the maximum missle launching speed is ~14 seconds for me with minimum setup of T9 bonus + Arcane Barrage.
