### ISSUE TITLE
Game doesn't load after most recent update

### ISSUE THREAD

**Issue by razage** [Heishe/idleraiders-second-run#752]
Whenever I try to load the game, i t downloads an error_report.txt file. Here's the contents of that file:

```json
{  
  "saveGame":42,
  "stackTrace":"TypeError: Cannot read property 'getBoundingBoxToWorld' of null\n    at a.addMouseOverListener (https://irsr.games.pitforest.de/game.min.js:3942:476)\n    at CreateInfoPopupHelper (https://irsr.games.pitforest.de/game.min.js:3041:93)\n    at ctor (https://irsr.games.pitforest.de/game.min.js:3175:184)\n    at c.<anonymous> (https://irsr.games.pitforest.de/game.min.js:101:328)\n    at new c (https://irsr.games.pitforest.de/game.min.js:100:166)\n    at c.onEnter (https://irsr.games.pitforest.de/game.min.js:3219:355)\n    at c.<anonymous> (https://irsr.games.pitforest.de/game.min.js:101:328)\n    at c.setNextScene (https://irsr.games.pitforest.de/game.min.js:531:392)\n    at c.drawScene (https://irsr.games.pitforest.de/game.min.js:525:245)\n    at c.mainLoop (https://irsr.games.pitforest.de/game.min.js:536:250)",
  "logs":"{\"log\":[]}",
  "version":"1.4.3",
  "versionNum":41,
  "errorMessage":"Cannot read property 'getBoundingBoxToWorld' of null"
}
```

**Comment by hamburml** [comment]
Hi razage,

have you tried clearing your browser cache? Remember, when you clear your cache you delete your local savegames. If you had cloud savegames they will be downloaded from our server.

Sorry for the inconvenience.
Michael

**Comment by razage** [comment]
I had tried hard reloading (shift-f5) but I didn't delete my cache. But one way or another, it ended up fixing itself later that day. Sorry for bugging you!

**Comment by hamburml** [comment]
When using 'hard reloading' or 'shift f5' stuff remember that when you are playing our game on kongregate that kongregate will be hard reloaded but not our game (depends on the browser) because it's embedded. It's easier to go directly to https://irsr.games.pitforest.de (you are automatically logged out when using this link), reload the page without cache, close it and open it via kongregate. Then it should work...

Why is this so messy you ask? Our game knows when it's loaded via kongregate and uses their api to log you on. When our game doesn't find the kongregate api you are automatically logged out from our game (but not from kongregate). Sorry, there is not a better way right now.
