### ISSUE TITLE
Game crashes when I unequip Basic Heal skillbooks

### ISSUE THREAD

**Issue by Carlese33** [Heishe/idleraiders-second-run#785]
Everytime I unequip or change the Basic Heal skillbooks from my priests my game crashes as soon as one of these priests heal a raider. I can not unequip or change my priests Basic Heal skillbooks. 
I attach the error report when I tried to change my skillbooks for Healstreak, but it also happens when I just unequip. 

What is causing the crash?

I tried to clear cache, tried it on Mozilla Firefox (I never opened Idle Raiders on Mozilla before), I don't have any other instances opened, and I have been experiencing this problem since I bought the Basic heal auto hit ancient widsom ability (I never tried to unequip them before). 

I attach the error file. 
[error_report (8).txt](https://github.com/Heishe/idleraiders-second-run/files/2082038/error_report.8.txt)

As soon as I open the game again, those Basic Heal skillbooks are equiped again.

**Comment by Talisca** [comment]
HealStreak is the culprit. BasicHeal triggered the HealStreak, but as you removed the BasicHeal-Skillbook it can not find the trigger-skill anymore. 

With the changeover of the new BasicHeal-Skillbook we missed the adaption of the HealStreak-Ability. It does not take the autohit abilities into account. This will be fixed with the next patch.

In the meantime you can either use the combination of BasicHeal-Skillbook + HealStreak-Skillbook or you do not use the HealStreak-Skillbook at all. Sorry :(

**Comment by hamburml** [comment]
We released v1.6. Please open a new issue if this happens again.
Thanks!
