### ISSUE TITLE
Suggestion List

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#84]
**Training**

Option to see individual stats and / or enter with only a part of your raiders. What you mainly want to test at these features is if X build is better than Y, with 10 raiders doing random critical hits and getting random buffs from skills and abilities there is to much RNG for this kind of test. Entering with just a selected team could fix this.

**Transmog:** 

Option to look like you did before you got any items.

**Equipment and statistics**

a)There is a pretty big list here, i think you could shorten it a bit like this: Instead of MAX HP and MAX Mana you could have a red and blue bar on the left side of the raider that is currently empty. It could just show full mana/hp instead of a moving bar.
b) To continue with part a, you could remove degeneration, since it is only a warrior stat, and have warrior regen stat say "1 (-2 OOC)" for 2 degeneration out of combat.
c) Attack speed need a name change or additional info. Like Attack speed/CDR or Attack/Casting speed to clarify it works for casting and skills.
d) If a skill is effected by other skills it should show somehow. For example, when you equip a fireball with  Ignite the fireball skill should get a description update saying "Crit chance increased by 8% (Ignite)".

**Changing areas**

I think it was mentioned already but those tiny buttons are not nice to change areas. I suggest using bigger buttons either at a)bottom left of the sceen, below our party, or at b)the bottom mid, next to our hotkeys, or c)just another bar like those you have at the right dedicated to area swapping. I would prefer one of the first 2 options.

**Inventory**

a)Can we have 4 buttons at the leftside of the menu, like we have sorting and deleting at the right side, dedicated to the 4 classes. When you click X class the items dedicated to this class turn grey/normal. So if we only want to see warrior/mage items we have those classes enabled etc.
b) Sorting equipment by rarity would be REALLY useful.

**Raider Upgrades**

I would like to test how balanced they are, they seem better priced than what they used to be and with less OP effects. Still a way to see how i got from a maximum of 3 upgrades to 4 would be nice, does it have to do with resets?

**Farming**

Areas 40-43 (and maybe higher, not sure). A sligthly less white background would be nice for our eyes, like 5-10% more towards grey would do the trick i think.

**RNG in Scholars tower.**

I just don't like the way it works. I build it and get a combo of 3 arcane books for my mage which makes him instantly op (7 magic missiles with 0 cd), someone else might get... 3x cold focus and not have the appropriate skill to pair it with. Its to luck based and having 6 mighty blow with 5k cost in 10 skill books is just frustrating.

I think the RNG here should be removed and replaced with this:
a) Categorize books into Tiers.
b) Clearing a higher level raid unlocks a new tier.
c) Every X hours you unlock a new spellbook from the available tiers. (Alternative to buy the plans from the wandering merchant for less rng.)
d) Every 1 hour all spellbooks unlocked get +1 quantity with a limit of Y.

Result: Rng of OP combos for your level removed, situations where every book you get is useless or to expensive lowered, strategy improved (for raid X you need a spellbook that unlock at merchant when you beat X-1, gather gold, buy from merchant, wait 1 hour, buy the book, progress or for example if you lack AOE dps you can focus on unlocking AOE skills etc).

**General**

Still haven't figured how to change raider names...

**Comment by askebv** [comment]
I agree with most of this. I'm not sure what you mean in 3a (Equipment and Statistics) though.

For point 4 (Changing Areas), I see it like this: In the vast majority of time, you want one of four things:
1. Go to a specific low level map (for gold and decent exp/time)
2. Change map back and forth to reset the map (for maps that are hard to clear)
3. Have auto-farm-increase on
4. Farm a specific map for drops (assuming this is still a thing)

And changing all the way from 40+ to level 5 or so, takes a lot of clicks. So perhaps we could get a way to go to a specific number, just by typing the number and pressing a button. Or perhaps a table of levels where you could click the one you wanted to go to it.
Or even better, navigate a map with e.g. 10 levels being visually represented per map. But that's for future ideas anyway.

Additionally, I neither have figured out what resources are. And what enchanting does, or how it's used. I did get several recipes though, and have "used" them (for learning how to make them or something).

And I guess I'll reference my prior list too: #53

**Comment by Ethismos** [comment]
At 3a i mean there is a huge list of statistics that its not so easy to read, you could move a few of them in other positions to make them easier to read. For example have max HP and MP as a bar next to the raiders portrait at the same menu. This way you get a shorter wall of text. Mainly a visual change, not to important overall.

As for your suggestion about changing farm levels quicker, yes, i hope this get a bit improved also, but i either raid or afk farm low levels most of the time so it wasn't much of an issue for me yet.

Also haven't done any enchanting either, i guess its not implemented at beta.

**Comment by askebv** [comment]
Just found out that there's another frost book that I didn't know about in the Scholar's Tower called "Chill". Also, if Challenging Cry and Protective Shield are abilities that I am supposed to get in there, then I haven't seen any of them yet. This is pretty much all I've seen:

![image](https://cloud.githubusercontent.com/assets/4981659/15791242/69b9a478-29d6-11e6-899f-2be5ca8e161f.png)

**Comment by Ethismos** [comment]
I got magic missile(x2), arcane barrage(x3), cold focus(x1), quickshot(x4), mighty blow(x6), war cry(x6), arcane bombardment (x2), chill(x1), arcane frenzy(x1) -seems underpowered, hitstreak(x1), charming shot(x3), multiple shots(x1), mark enemy (x2), cleave(x3), Area of Effect Heal (x3), Ignite (x2), Inner Combustion (x1), Rallying Cry (x2), Crippling Shot(x1), Flash Heal (x2), Taunt (x1).

I think it is totally random and can include most, if not all, skillbooks. I haven't got the shield block at all, or bulwark. Also i got from drop a skillbook that is level 2, it is probably an upgraded version from raids only, i don't have the normal one to compare the effects though....

![](http://i.imgur.com/nbR1bGX.jpg)

**Comment by askebv** [comment]
Yeah, Arcane Frenzy is probably only really good if you have the mana regen to support it. I just have it on because it seems like the best I can do with what I have. My mages are pretty much mana-starved all the time anyway, so I don't feel like it matters too much.

But yeah, it's evident that we have been given a lot of different skills from our RNGods. And some very useful, and the absence of others are very impractical. All the more reason to something like your suggestion of tiers, in my opinion.

EDIT: This is the frost shard in level 1 btw:

![image](https://cloud.githubusercontent.com/assets/4981659/15793838/08153230-29e7-11e6-81ab-1b5995355185.png)

**Comment by TravisGesslein** [comment]
Took a while to respond to this, very busy! 
- Training

I have another idea for this. I think we will implement a 'damage meter' (with options for HPS, damage taken, and other stats of course) for the raiders similar to what you know from many MMO addons. A kind of view that shows 10 normalized bars with character icons to the left indicating which raider it belongs to, and the length of the bar shows damage relative to the other raiders. Plus some fonts on top to show the actual damage numbers etc. 

The raider training system could then still be used well for testing your entire raider setup in an artificial environment. What do you think about it?
- Transmogs:

Yep, but not as an option. We can do this more naturally by adding purely cosmetic items (which we will do anyways) that give you back the classic look, so to speak.
- Equipment and stats

a) I don't think that's necessary. We have bars for the character views on the top left because it's important to see the stat 'at a quick glance', so seeing a red bar and knowing a raider has low HP has a lot of benefit. For the stats in the stat screen however, you usually have a lot of time to look at them so I don't think it's worth the implementation time to give the HP some special bars (not even sure if that would be a good method to indicate a maximum value of something). Unless you mean that the text is actually hard to read because it's formatted badly. I don't think this is the case currently, but we can improve this a lot by e.g. adding lines between the stats and stuff like that.
b) That's not how the stat works, the degeneration is actually active during combat! That's why rage generation or items that improve regeneration for warriors are so powerful, by default the warrior makes almost no rage if they are not being attacked themselves. It's also only effectively a warrior-only stat by now, we want to keep all of these for all classes because it enables us to add unique items to the game that play with these stats in an interesting way. 
c) This is a good idea, we should probably add mouse-over infos that says like "increases the attack/casting speed of the raider and speeds up cooldown durations by the same amount" etc. I will add it to internal to do list.
d) This might be a big effort code-implementation and design wise. I will add it to a to-do list but not sure when we will get around to it.

Changing areas:

Making the buttons bigger is no problem, but what's the reason for moving them somewhere else? We'd like to keep all the "activity" ui related stuff at the top, because it's the center of what you do, so to speak. 

Inventory

Already implemented as you rpobably already know!

Raider Upgrades

Yes you get one extra for first clears (in the savegame, not just the current reset) of each raid. We will deal with this in the future using the book of prophecies, which will be used (among other things) to show the player milestones of what they can do basically. We will add one for each raid that can be cleared, and tell you what you get for it.

Farming:

Yup, we can do that

RNG in Scholar's Tower:
Yup, we touched on this in another issue (can't find it right now), main rough points are:
- Skills in the Scholar's Tower aren't supposed to be (much) better or worse than other skills, this should be solved with balancing. Exception to this are clearly situational ones like Charming Shot. We can divide them into different tiers based on that.
- The randomness needs to be dealt with though, and we will

General

Changing raider names isn't in anymore, we should probably add it back :hankey:

**Comment by askebv** [comment]
@Heishe #289

**Comment by Ethismos** [comment]
@Heishe 

Training: 
This should work equally good.

Transmog: 
As long as the option exists i guess it would be easier to do it with other items and i am fine with that.

Equipment and stats: 
A) Ok, its mostly a visual change and not to important. I think people enjoy and use more some bars than simple text, so keeping the text to a minimum and changing maximum mana/health to bars, dots, squares etc would look better. It might not even be the case and it is not to important overall towaste time on it.
b) Useful info.
c) Good alternative.
d) I know, take your time with it.

Changing areas:
I think it would be more user friendly to have all the 5-6 buttons for areas at their own place instead of having a menu pop up like now.  I find that having to open that menu every 30 seconds to choose what i want to do is bad use of space and i would rather have my options always visible somewhere. If you like to keep them on the right side its fine for me, but in case you need more space you could move them or the menu/changelog/reddit area somewhere else.

Inventory: 
Many good changed there overall.

Farming:
Thanks, a bit to bright for me. A very small change should be fine.

RNG in Scholar's Tower:
Ok, as long as there are no imbalances, like one person starting with fireball, fireball, ignite and another with 3x calming shot at their tower any solution is fine for me.

Balancing will not be to hard imo. With some nerfs to arcane spec which currently has best damage per second AND mana AND best scaling with or without critical build with the available gear there are 3 very clear situational paths : Fast cast with debuffs, big cheap criticals, fast mana usage.

It may get harder later on though depending on how your gear stats scale. If for example you had a non-unique late game item with critical chance +15% and critcal damage +100% i think fire would overpower even the current arcane build and the low debuffs of frost would be insignificant.

General:

I would like it back, but if you do not add it then you should remove the option to short by name, as it is just a completely random sorting !

**Comment by TravisGesslein** [comment]
I'm cleaning up the issue tracker a bit so I'm closing these suggestions threads. I'll create an internal document for us that references all of these so we don't forget about them!
