### ISSUE TITLE
Well building buff (part 2)

### ISSUE THREAD

**Issue by Ethismos** [Heishe/idleraiders-second-run#90]
At part 1 i noticed the buff only mentions rage.

Now i also noticed that the building says 3% and the buff is 2% for every class.

**Comment by askebv** [comment]
You also mentioned that in the other topic :P

#69 <-- that's your old issue

If you mean that one well says 3% in your buff, then we have it differently, since mine says 6% and I have three of them:

![image](https://cloud.githubusercontent.com/assets/4981659/15784903/ed246f36-29b4-11e6-9b63-e2cbb398e8d3.png)

**Comment by Ethismos** [comment]
Yeah, i thought it was a tooltip issue at that point. I checked the stats and it actually GIVES 2% that it says at the buff while the building says 3%. Eh, anyway :)

**Comment by askebv** [comment]
Ah you're right. It actually gives 2% to all raiders.

@Heishe So **to summarize**:
- Tooltip of the buff should say "Energy" or "Mana/Rage/Focus" instead of rage.
- Tooltip of the building should say 2% instead of 3%

**Comment by Ethismos** [comment]
Yeah!
