### ISSUE TITLE
Red priestess roaming

### ISSUE THREAD

**Issue by askebv** [Heishe/idleraiders-second-run#92]
This is probably related to #28 and perhaps #80 as well.

These red priestesses are sure having fun. One of them must be doing a dance ceremony at the temple:

![image](https://i.gyazo.com/c398a067742a2a64862dbf68ce7072c6.gif)

She was stuck there for several minutes. But then finally got free. I didn't see how, but I suspect it was because raiders arrived that she decided to try heal.

**Comment by askebv** [comment]
I captured another one happening. It seems they're really happy to be stuck on bottom left corners:

![image](https://i.gyazo.com/20ec7c99eb1aca4d7844033a0a2ebe19.gif)

As you can see in the final second, she manages to get free. But she was there for pretty long. And she continued to do it a bit afterwards - but then finally she found another place to be.

**Comment by TravisGesslein** [comment]
Alright, we changed how raiders move. They now use various steering algorithms for every step they take. It's impossible to avoid all problematic situations (like multiple raiders who share the same goal bumping into each other) without cooperative path finding and decision making (which would kill performance unfortunately), but the new way we do things should fix a lot of issues. 

One thing that will be missing is tanks pushing other raiders out of their way. We will create a new raider upgrade for that, which will make other raiders actually wait until the tanks are in front, instead of trying to solve this with movement (it's more robust). Just mentioning this so there's no confusion - that behavior will not be in beta patch 9. I will create a separate issue for it.
