### ISSUE TITLE
Skill priority list is reset to default

### ISSUE THREAD

**Issue by TravisGesslein** [Heishe/idleraiders-second-run#99]
If you restart the game and notice your skill priority list not being saved (seemingly being reset to default), its because the game detected that there was something wrong with it and restorted it to default to prevent the game from crashing.

If this happens to you, it would be awesome if you could tell us how to reproduce the problem and trigger the skill order reset.

**Comment by TravisGesslein** [comment]
See #94

**Comment by Ethismos** [comment]
Ok, so i caused the bug when i tried to manage my new skills after i bought a bunch of spellbooks from the merchant.

Way to reproduce the skill reset with what i have now:
3x Saving throw. 3x Rallying cry. A warrior.
Equip **one** at your warrior. 
![Image1](http://i.imgur.com/8zzMraD.jpg)
Equip **two** at your warrior. - Everything normal.
![Image2](http://i.imgur.com/5BNjCEi.jpg)
Equip **three** at your warrior.
![Image3](http://i.imgur.com/n974ri4.jpg)
Equip **one** rallying cry
![Image4](http://i.imgur.com/1TbC56R.jpg)

Try to move around any skill, get random stuff like this:
![Image5](http://i.imgur.com/w4DFY5A.jpg)
This screenshot was taken with 0 skillbooks equipped.

I get a skill order reset at every step if i try to load the save game, maybe except 2 but can't really test that because its the same thing...

**Comment by TravisGesslein** [comment]
Thank you and @Muskar for the detailled descriptions, working on this fix now.
